// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, ToolforgeError_Serialize>(__TAURI_INVOKE("app_info")),
	appPaths: () => typedError<AppPathsDto, ToolforgeError_Serialize>(__TAURI_INVOKE("app_paths")),
	systemStatus: () => typedError<SystemStatus, ToolforgeError_Serialize>(__TAURI_INVOKE("system_status")),
	settingsGet: () => typedError<Settings, ToolforgeError_Serialize>(__TAURI_INVOKE("settings_get")),
	/**
	 *  局部更新设置。
	 * 
	 *  ## 顺序是有讲究的
	 * 
	 *  1. **改内存**（用户立刻看到效果）
	 *  2. **落盘**（关掉应用还在）
	 *  3. **把变化作用到运行时**（并发度 → 队列；AI 配置 → 重建客户端）
	 * 
	 *  第 3 步不能漏：`AiClient` 在构造时就把 base_url / 模型 / Key 固化进连接池了，
	 *  只改 `settings` 不重建客户端，界面上显示"已改成 gpt-4o"，
	 *  实际请求还打给老模型 —— 这类"设置了但没生效"的 bug 最难被发现。
	 */
	settingsPatch: (patch: SettingsPatch_Deserialize) => typedError<Settings, ToolforgeError_Serialize>(__TAURI_INVOKE("settings_patch", { patch })),
	jobsList: (req: JobsListRequest_Deserialize) => typedError<JobsSnapshot_Serialize, ToolforgeError_Serialize>(__TAURI_INVOKE("jobs_list", { req })),
	jobsGet: (jobId: string) => typedError<{
	id: JobId,
	kind: JobKind,
	title: string,
	status: JobStatus,
	progress: JobProgress_Serialize,
	createdAt: string,
	startedAt?: string | null,
	finishedAt?: string | null,
	error?: ToolforgeError_Serialize | null,
	/**  日志只保留尾部 N 条（见 [`Job::LOG_TAIL_LIMIT`]），避免长任务把内存吃光 */
	logs: JobLogEntry[],
	/**  产出文件路径 */
	outputs: string[],
	/**  总条目数 / 已完成 / 失败（批量任务用） */
	totalItems: number,
	completedItems: number,
	failedItems: number,
} | null, ToolforgeError_Serialize>(__TAURI_INVOKE("jobs_get", { jobId })),
	jobsCancel: (jobId: string) => typedError<Job_Serialize, ToolforgeError_Serialize>(__TAURI_INVOKE("jobs_cancel", { jobId })),
	jobsClearFinished: () => typedError<number, ToolforgeError_Serialize>(__TAURI_INVOKE("jobs_clear_finished")),
	jobsStats: () => typedError<JobStats, ToolforgeError_Serialize>(__TAURI_INVOKE("jobs_stats")),
	/**  任务重试。仅对注册过重放闭包的任务有效（插件运行可以，引擎安装与 AI 生成不行）。 */
	jobsRetry: (jobId: string) => typedError<string, ToolforgeError_Serialize>(__TAURI_INVOKE("jobs_retry", { jobId })),
	enginesCatalog: () => typedError<EngineEntry_Serialize[], ToolforgeError_Serialize>(__TAURI_INVOKE("engines_catalog")),
	enginesProbeAll: () => typedError<EngineEntry_Serialize[], ToolforgeError_Serialize>(__TAURI_INVOKE("engines_probe_all")),
	enginesProbe: (engineId: string) => typedError<EngineStatus_Serialize, ToolforgeError_Serialize>(__TAURI_INVOKE("engines_probe", { engineId })),
	/**
	 *  安装引擎。
	 * 
	 *  **不会立刻返回成功**：它创建一个任务并立即返回 `jobId`，
	 *  下载进度通过 `toolforge://event` 里的 `engineDownloadProgress` 事件回流。
	 */
	enginesInstall: (req: EngineInstallRequest) => typedError<string, ToolforgeError_Serialize>(__TAURI_INVOKE("engines_install", { req })),
	/**
	 *  列出全部模型权重及其状态。
	 * 
	 *  `downloadable` 是给界面用的：**没有配置下载源的模型必须提前显示为不可下载**，
	 *  而不是让用户点一下、等几秒、再收到一个"没有配置 SHA-256"的错误。
	 */
	modelsList: () => typedError<ModelEntry_Serialize[], ToolforgeError_Serialize>(__TAURI_INVOKE("models_list")),
	/**  下载一个模型权重。 */
	modelsInstall: (req: ModelInstallRequest) => typedError<string, ToolforgeError_Serialize>(__TAURI_INVOKE("models_install", { req })),
	/**  删除一个已下载的模型权重，释放磁盘。 */
	modelsRemove: (modelId: string) => typedError<boolean, ToolforgeError_Serialize>(__TAURI_INVOKE("models_remove", { modelId })),
	pluginsList: () => typedError<PluginsSnapshot_Serialize, ToolforgeError_Serialize>(__TAURI_INVOKE("plugins_list")),
	pluginsGet: (pluginId: string) => typedError<{
	summary: PluginSummary_Serialize,
	manifest: PluginManifest_Serialize,
	rawYaml: string,
	/**  用户实际授予的能力 */
	granted: PermissionSet,
	/**  插件目录下的文件列表（相对路径） */
	files: string[],
	readme?: string | null,
	/**  运行时健康状态（L2/L3 才有意义） */
	runtimeStatus?: string | null,
} | null, ToolforgeError_Serialize>(__TAURI_INVOKE("plugins_get", { pluginId })),
	pluginsReload: () => typedError<number, ToolforgeError_Serialize>(__TAURI_INVOKE("plugins_reload")),
	/**  校验一份插件来源，**不落盘**。 */
	pluginsValidate: (req: ValidatePluginRequest) => typedError<ValidatePluginResponse_Serialize, ToolforgeError_Serialize>(__TAURI_INVOKE("plugins_validate", { req })),
	/**
	 *  安装插件。
	 * 
	 *  ## 两道硬门（在前端之上再加一层，因为前端可以被绕过）
	 * 
	 *  * [`InstallPluginRequest::permissions_acknowledged`] 必须为 `true`；
	 *  * 若插件是 L3（Python），[`InstallPluginRequest::executable_code_acknowledged`]
	 *    也必须为 `true`。
	 * 
	 *  注意：**安装后插件仍然是禁用且零授权的状态**，还要再走 `plugins_grant` +
	 *  `plugins_set_enabled`。这不是啰嗦，而是让"看权限"和"用它"成为两个不同的动作。
	 */
	pluginsInstall: (req: InstallPluginRequest) => typedError<InstallReport_Serialize, ToolforgeError_Serialize>(__TAURI_INVOKE("plugins_install", { req })),
	pluginsGrant: (req: GrantPermissionsRequest) => typedError<PluginSummary_Serialize, ToolforgeError_Serialize>(__TAURI_INVOKE("plugins_grant", { req })),
	pluginsSetEnabled: (pluginId: string, enabled: boolean) => typedError<PluginSummary_Serialize, ToolforgeError_Serialize>(__TAURI_INVOKE("plugins_set_enabled", { pluginId, enabled })),
	pluginsUninstall: (pluginId: string) => typedError<null, ToolforgeError_Serialize>(__TAURI_INVOKE("plugins_uninstall", { pluginId })),
	pluginsAudit: (limit: number) => typedError<AuditSnapshot_Serialize, ToolforgeError_Serialize>(__TAURI_INVOKE("plugins_audit", { limit })),
	/**
	 *  运行插件。立即返回 `jobId`。
	 * 
	 *  ## 多文件输入会真的逐个处理
	 * 
	 *  这是个修过的坑：第一版把「12 个输入文件」塞进一次流水线调用，
	 *  而 `L1 执行器` 的 `${src}` 只绑定第一个路径 —— 结果是任务标题写着
	 *  `插件名 · 12`、实际只处理了 1 张、然后**成功结束**。用户看到的是"12 个全成功"，
	 *  这是最糟糕的一类 bug（静默地少干活）。
	 * 
	 *  现在由**命令层扇出**：把主输入端口展开成 N 个单文件批次，逐批调用执行器，
	 *  用 `ctx.step` 上报 `处理 3/12`。这也让 `l1.rs` 模块文档里
	 *  "批量由命令层展开" 那句话变成事实。
	 */
	pluginsRun: (req: RunPluginRequest) => typedError<RunPluginResponse, ToolforgeError_Serialize>(__TAURI_INVOKE("plugins_run", { req })),
	pipelineNodes: () => typedError<NodeCatalogResponse_Serialize, ToolforgeError_Serialize>(__TAURI_INVOKE("pipeline_nodes")),
	aiTestConnection: () => typedError<AiTestConnectionResponse_Serialize, ToolforgeError_Serialize>(__TAURI_INVOKE("ai_test_connection")),
	/**
	 *  用自然语言生成插件草稿。
	 * 
	 *  ## 返回的是草稿，不是插件
	 * 
	 *  这个命令**不写盘、不装载**。它返回 [`AiGenerateResponse`]：
	 *  原始草稿 + 审核报告。安装必须由用户在前端确认后另调 `plugins_install`。
	 *  这样即使模型被提示词注入攻陷，它也只能产出"用户看得见的一份草稿"。
	 */
	aiGenerate: (req: AiGenerateRequest_Deserialize) => typedError<AiGenerateResponse_Serialize, ToolforgeError_Serialize>(__TAURI_INVOKE("ai_generate", { req })),
	/**  对一段（可能被用户手改过的）插件文本重新审核。 */
	aiReviewDraft: (raw: string) => typedError<SecurityReview_Serialize, ToolforgeError_Serialize>(__TAURI_INVOKE("ai_review_draft", { raw })),
};

/* Constants */
export const EVENT_CHANNEL = "toolforge://event" as const;

export const PLUGIN_API_VERSION = "toolforge/v1" as const;

/* Types */
/**
 *  AI 生成的**内存草稿**。
 * 
 *  它**没有**任何写盘能力 —— 这是刻意的类型设计：想看盘就必须显式转成
 *  [`toolforge_core::plugin::PluginSource`]，而那个转换发生在外壳层、
 *  在用户点了"安装"之后。
 */
export type AiDraft = {
	/**  产生这次草稿的原始需求（写进溯源信息） */
	prompt: string,
	/**  使用的模型标识 */
	model: string,
	/**  解析出来的文件 */
	files: DraftFile[],
	/**  原始文本（前端"查看原始输出"用） */
	raw: string,
};

export type AiGenerateRequest = AiGenerateRequest_Serialize | AiGenerateRequest_Deserialize;

export type AiGenerateRequest_Deserialize = {
	description: string,
	/**  是否允许生成 Python 代码插件（默认 false） */
	allowPython?: boolean,
	categoryHint?: string | null,
};

export type AiGenerateRequest_Serialize = {
	description: string,
	/**  是否允许生成 Python 代码插件（默认 false） */
	allowPython: boolean,
	categoryHint?: string | null,
};

/**  生成结果 = 草稿 + 审核报告。**不含任何"已安装"语义。** */
export type AiGenerateResponse = AiGenerateResponse_Serialize | AiGenerateResponse_Deserialize;

/**  生成结果 = 草稿 + 审核报告。**不含任何"已安装"语义。** */
export type AiGenerateResponse_Deserialize = {
	draft: AiDraft,
	review: SecurityReview_Deserialize,
	provider: string,
	model: string,
};

/**  生成结果 = 草稿 + 审核报告。**不含任何"已安装"语义。** */
export type AiGenerateResponse_Serialize = {
	draft: AiDraft,
	review: SecurityReview_Serialize,
	provider: string,
	model: string,
};

/**
 *  记录"这个插件是 AI 生成的"，以及人工审核的状态。
 * 
 *  宿主**不会**因为 `reviewedAt` 有值就自动放行 —— 放行的唯一依据是
 *  用户授予的 [`PermissionSet`]。这里只是审计线索。
 */
export type AiProvenance = AiProvenance_Serialize | AiProvenance_Deserialize;

/**
 *  记录"这个插件是 AI 生成的"，以及人工审核的状态。
 * 
 *  宿主**不会**因为 `reviewedAt` 有值就自动放行 —— 放行的唯一依据是
 *  用户授予的 [`PermissionSet`]。这里只是审计线索。
 */
export type AiProvenance_Deserialize = {
	generated: boolean,
	model?: string | null,
	prompt?: string | null,
	/**  ISO-8601 */
	generatedAt?: string | null,
	reviewedAt?: string | null,
	/**  内容哈希（`sha256:...`）。装载前校验，防止装载后被替换。 */
	sourceHash?: string | null,
};

/**
 *  记录"这个插件是 AI 生成的"，以及人工审核的状态。
 * 
 *  宿主**不会**因为 `reviewedAt` 有值就自动放行 —— 放行的唯一依据是
 *  用户授予的 [`PermissionSet`]。这里只是审计线索。
 */
export type AiProvenance_Serialize = {
	generated: boolean,
	model?: string | null,
	prompt?: string | null,
	/**  ISO-8601 */
	generatedAt?: string | null,
	reviewedAt?: string | null,
	/**  内容哈希（`sha256:...`）。装载前校验，防止装载后被替换。 */
	sourceHash?: string | null,
};

/**  提供方类型（决定默认的 base_url 与是否需要 Key） */
export type AiProviderKind = 
/**  OpenAI 官方 */
"openAi" | 
/**  DeepSeek */
"deepSeek" | 
/**  阿里云百炼 / 通义千问（兼容模式） */
"dashScope" | 
/**  月之暗面 Kimi */
"moonshot" | 
/**  本地 Ollama */
"ollama" | 
/**  本地 LM Studio */
"lmStudio" | 
/**  任意 OpenAI 兼容端点 */
"custom";

/**
 *  AI 设置。**API Key 不在这里** —— 它存在内存里，只有用户显式打开
 *  「记住 API Key」时才会另存到 `<数据目录>/ai-key.txt`。
 *  无论如何它都不会落到这个会序列化给前端的结构体上。
 */
export type AiSettings = {
	provider?: AiProviderKind,
	baseUrl?: string,
	model?: string,
	/**  只读：是否已经配置过 Key */
	hasKey?: boolean,
	temperature?: number | null,
	/**
	 *  是否把 Key 落盘（默认**否**）。
	 * 
	 *  这个字段存在的原因是：原来的实现把 Key 只放在内存里，界面上却写着
	 *  「存在本机内存与系统钥匙串里」—— 钥匙串从来没接过。与其继续骗人，
	 *  不如把选择权交给用户，并说清代价：打开 = 明文存在数据目录下。
	 */
	persistApiKey?: boolean,
};

export type AiTestConnectionResponse = AiTestConnectionResponse_Serialize | AiTestConnectionResponse_Deserialize;

export type AiTestConnectionResponse_Deserialize = {
	ok: boolean,
	models: string[],
	error?: string | null,
};

export type AiTestConnectionResponse_Serialize = {
	ok: boolean,
	models: string[],
	error?: string | null,
};

export type AppEvent = AppEvent_Serialize | AppEvent_Deserialize;

export type AppEvent_Deserialize = 
/**  任务整体状态变化（排队 → 运行 → 结束，或标题/产出变化） */
({ type: "jobUpdated"; job: Job_Deserialize }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; jobId?: never; level?: never; message?: never; pluginId?: never; progress?: never; requestId?: never; severity?: never; speedBps?: never; status?: never; subject?: never; title?: never; total?: never } | 
/**
 *  任务进度变化。
 * 
 *  **单独走一个事件而不是重推整个 `Job`**：转码任务一秒能产出几十次进度，
 *  每次都序列化整条 Job（含日志数组）会把 IPC 打爆。
 *  队列内部已经做了 100ms 节流。
 */
({ type: "jobProgressHint"; jobId: string; progress: JobProgress_Deserialize }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; job?: never; level?: never; message?: never; pluginId?: never; requestId?: never; severity?: never; speedBps?: never; status?: never; subject?: never; title?: never; total?: never } | 
/**  任务新增日志行。**单独走一个事件**，避免日志刷屏时反复推送整个 Job。 */
({ type: "jobLog"; jobId: string; entry: JobLogEntry }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; error?: never; errorMessage?: never; job?: never; level?: never; message?: never; pluginId?: never; progress?: never; requestId?: never; severity?: never; speedBps?: never; status?: never; subject?: never; title?: never; total?: never } | 
/**  任务终结（前端据此弹通知、刷新文件列表、决定是否重试） */
({ type: "jobFinished"; jobId: string; status: JobStatus; title: string; errorMessage?: string | null }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; job?: never; level?: never; message?: never; pluginId?: never; progress?: never; requestId?: never; severity?: never; speedBps?: never; subject?: never; total?: never } | 
/**  引擎探测/安装状态变化 */
({ type: "engineStatusChanged"; status: EngineStatus_Deserialize }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; job?: never; jobId?: never; level?: never; message?: never; pluginId?: never; progress?: never; requestId?: never; severity?: never; speedBps?: never; subject?: never; title?: never; total?: never } | 
/**  引擎下载进度（`downloaded` / `total` 单位是字节；`total` 为 0 表示未知） */
({ type: "engineDownloadProgress"; engineId: string; downloaded: number; total: number; speedBps: number | null }) & { delta?: never; detail?: never; entry?: never; error?: never; errorMessage?: never; job?: never; jobId?: never; level?: never; message?: never; pluginId?: never; progress?: never; requestId?: never; severity?: never; status?: never; subject?: never; title?: never } | 
/**  插件集合发生变化（装载/卸载/启用/授权） */
({ type: "pluginChanged"; pluginId: string }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; job?: never; jobId?: never; level?: never; message?: never; progress?: never; requestId?: never; severity?: never; speedBps?: never; status?: never; subject?: never; title?: never; total?: never } | 
/**  插件运行时输出（L2 的 log 宿主函数 / L3 的 stderr） */
({ type: "pluginLog"; pluginId: string; level: string; message: string }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; job?: never; jobId?: never; progress?: never; requestId?: never; severity?: never; speedBps?: never; status?: never; subject?: never; title?: never; total?: never } | 
/**
 *  **安全事件**：插件越权、哈希不匹配、AI 产出未通过审核。
 *  前端应当以醒目方式提示，并写入审计日志。
 */
({ type: "securityAlert"; severity: string; title: string; detail: string; subject?: string | null }) & { delta?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; job?: never; jobId?: never; level?: never; message?: never; pluginId?: never; progress?: never; requestId?: never; speedBps?: never; status?: never; total?: never } | 
/**  AI 流式输出增量（插件生成过程实时显示） */
({ type: "aiDelta"; requestId: string; delta: string }) & { detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; job?: never; jobId?: never; level?: never; message?: never; pluginId?: never; progress?: never; severity?: never; speedBps?: never; status?: never; subject?: never; title?: never; total?: never } | 
/**  AI 生成结束 */
({ type: "aiDone"; requestId: string; error?: string | null }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; errorMessage?: never; job?: never; jobId?: never; level?: never; message?: never; pluginId?: never; progress?: never; severity?: never; speedBps?: never; status?: never; subject?: never; title?: never; total?: never } | 
/**  通用提示（前端转成 toast） */
({ type: "toast"; level: string; title: string; message?: string | null }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; job?: never; jobId?: never; pluginId?: never; progress?: never; requestId?: never; severity?: never; speedBps?: never; status?: never; subject?: never; total?: never };

export type AppEvent_Serialize = 
/**  任务整体状态变化（排队 → 运行 → 结束，或标题/产出变化） */
({ type: "jobUpdated"; job: Job_Serialize }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; jobId?: never; level?: never; message?: never; pluginId?: never; progress?: never; requestId?: never; severity?: never; speedBps?: never; status?: never; subject?: never; title?: never; total?: never } | 
/**
 *  任务进度变化。
 * 
 *  **单独走一个事件而不是重推整个 `Job`**：转码任务一秒能产出几十次进度，
 *  每次都序列化整条 Job（含日志数组）会把 IPC 打爆。
 *  队列内部已经做了 100ms 节流。
 */
({ type: "jobProgressHint"; jobId: string; progress: JobProgress_Serialize }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; job?: never; level?: never; message?: never; pluginId?: never; requestId?: never; severity?: never; speedBps?: never; status?: never; subject?: never; title?: never; total?: never } | 
/**  任务新增日志行。**单独走一个事件**，避免日志刷屏时反复推送整个 Job。 */
({ type: "jobLog"; jobId: string; entry: JobLogEntry }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; error?: never; errorMessage?: never; job?: never; level?: never; message?: never; pluginId?: never; progress?: never; requestId?: never; severity?: never; speedBps?: never; status?: never; subject?: never; title?: never; total?: never } | 
/**  任务终结（前端据此弹通知、刷新文件列表、决定是否重试） */
({ type: "jobFinished"; jobId: string; status: JobStatus; title: string; errorMessage?: string | null }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; job?: never; level?: never; message?: never; pluginId?: never; progress?: never; requestId?: never; severity?: never; speedBps?: never; subject?: never; total?: never } | 
/**  引擎探测/安装状态变化 */
({ type: "engineStatusChanged"; status: EngineStatus_Serialize }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; job?: never; jobId?: never; level?: never; message?: never; pluginId?: never; progress?: never; requestId?: never; severity?: never; speedBps?: never; subject?: never; title?: never; total?: never } | 
/**  引擎下载进度（`downloaded` / `total` 单位是字节；`total` 为 0 表示未知） */
({ type: "engineDownloadProgress"; engineId: string; downloaded: number; total: number; speedBps: number | null }) & { delta?: never; detail?: never; entry?: never; error?: never; errorMessage?: never; job?: never; jobId?: never; level?: never; message?: never; pluginId?: never; progress?: never; requestId?: never; severity?: never; status?: never; subject?: never; title?: never } | 
/**  插件集合发生变化（装载/卸载/启用/授权） */
({ type: "pluginChanged"; pluginId: string }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; job?: never; jobId?: never; level?: never; message?: never; progress?: never; requestId?: never; severity?: never; speedBps?: never; status?: never; subject?: never; title?: never; total?: never } | 
/**  插件运行时输出（L2 的 log 宿主函数 / L3 的 stderr） */
({ type: "pluginLog"; pluginId: string; level: string; message: string }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; job?: never; jobId?: never; progress?: never; requestId?: never; severity?: never; speedBps?: never; status?: never; subject?: never; title?: never; total?: never } | 
/**
 *  **安全事件**：插件越权、哈希不匹配、AI 产出未通过审核。
 *  前端应当以醒目方式提示，并写入审计日志。
 */
({ type: "securityAlert"; severity: string; title: string; detail: string; subject?: string | null }) & { delta?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; job?: never; jobId?: never; level?: never; message?: never; pluginId?: never; progress?: never; requestId?: never; speedBps?: never; status?: never; total?: never } | 
/**  AI 流式输出增量（插件生成过程实时显示） */
({ type: "aiDelta"; requestId: string; delta: string }) & { detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; job?: never; jobId?: never; level?: never; message?: never; pluginId?: never; progress?: never; severity?: never; speedBps?: never; status?: never; subject?: never; title?: never; total?: never } | 
/**  AI 生成结束 */
({ type: "aiDone"; requestId: string; error?: string | null }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; errorMessage?: never; job?: never; jobId?: never; level?: never; message?: never; pluginId?: never; progress?: never; severity?: never; speedBps?: never; status?: never; subject?: never; title?: never; total?: never } | 
/**  通用提示（前端转成 toast） */
({ type: "toast"; level: string; title: string; message?: string | null }) & { delta?: never; detail?: never; downloaded?: never; engineId?: never; entry?: never; error?: never; errorMessage?: never; job?: never; jobId?: never; pluginId?: never; progress?: never; requestId?: never; severity?: never; speedBps?: never; status?: never; subject?: never; total?: never };

/**
 *  应用元信息（前端「关于」页用）
 * 
 *  同时派生 `Deserialize`：它会被嵌进 [`crate::AppInfo`] 所在的
 *  `SystemStatus` 里，而后者需要能被反序列化（测试与未来的 CLI 都用得上）。
 */
export type AppInfo = {
	name: string,
	version: string,
	tauriVersion: string,
	rustVersion: string,
	pluginApiVersion: string,
	buildProfile: string,
};

/**  应用目录布局（设置页「打开目录」按钮用） */
export type AppPathsDto = {
	entries: PathEntry[],
};

export type AuditEvent = AuditEvent_Serialize | AuditEvent_Deserialize;

/**  审计事件类型。**只增不改**：改名会让历史日志失去可读性。 */
export type AuditEventKind = 
/**  插件被安装 */
"installed" | 
/**  插件被卸载 */
"uninstalled" | 
/**  用户授予了能力 */
"permissionGranted" | 
/**  用户收回了能力 */
"permissionRevoked" | 
/**  **检测到权限扩张**（新版本声明了旧版本没有的能力） */
"privilegeEscalation" | 
/**  **运行时越权被拦截** —— 用了没声明/没授权的能力 */
"capabilityViolation" | 
/**
 *  **路径逃逸被拦截** —— 插件试图访问授权根之外的路径。
 * 
 *  与 [`AuditEventKind::CapabilityViolation`] 分开记，因为它们的**排查含义不同**：
 *  前者是"插件声明漏了/用户没授权"，后者是"有人在试探沙箱边界"。
 *  事后取证时这两件事的严重程度不一样，混在一起就分不出来了。
 * 
 *  这条是被一次真机测试逼出来的：我装了一个步骤里写死
 *  `C:\Windows\System32\drivers\etc\hosts` 的恶意插件并运行，任务被正确拒绝，
 *  **但审计日志里什么都没有** —— 因为拦截来自 `PathResolver`（`PermissionDenied`），
 *  而当时的审计钩子只认能力裁决的 `PluginCapabilityViolation`。
 */
"pathEscapeBlocked" | 
/**  清单校验失败 */
"validationFailed" | 
/**  哈希不匹配（装载时或下载时） */
"integrityFailure" | 
/**  AI 生成的插件通过审核并落盘 */
"aiDraftAccepted" | 
/**  AI 生成的插件被拒绝 */
"aiDraftRejected";

export type AuditEvent_Deserialize = {
	/**  ISO-8601 */
	at: string,
	kind: AuditEventKind,
	/**  相关插件 / 引擎 / 请求的标识 */
	subject?: string | null,
	/**  人类可读的摘要 */
	summary: string,
	/**
	 *  结构化补充信息，**以 JSON 文本形式存放**。
	 * 
	 *  为什么不用 `serde_json::Value`：它是无界递归类型
	 *  （`Value` → `Vec<Value>` → `Value`），specta 导出时会产生无限展开的 TS 类型
	 *  并直接报错。存成字符串后前端按需 `JSON.parse(e.detail)` 即可，
	 *  而写入端（[`AuditEvent::detail`]）仍然接受结构化值。
	 */
	detail?: string | null,
};

export type AuditEvent_Serialize = {
	/**  ISO-8601 */
	at: string,
	kind: AuditEventKind,
	/**  相关插件 / 引擎 / 请求的标识 */
	subject?: string | null,
	/**  人类可读的摘要 */
	summary: string,
	/**
	 *  结构化补充信息，**以 JSON 文本形式存放**。
	 * 
	 *  为什么不用 `serde_json::Value`：它是无界递归类型
	 *  （`Value` → `Vec<Value>` → `Value`），specta 导出时会产生无限展开的 TS 类型
	 *  并直接报错。存成字符串后前端按需 `JSON.parse(e.detail)` 即可，
	 *  而写入端（[`AuditEvent::detail`]）仍然接受结构化值。
	 */
	detail?: string | null,
};

export type AuditSnapshot = AuditSnapshot_Serialize | AuditSnapshot_Deserialize;

export type AuditSnapshot_Deserialize = {
	events: AuditEvent_Deserialize[],
	files: string[],
	dir: string,
};

export type AuditSnapshot_Serialize = {
	events: AuditEvent_Serialize[],
	files: string[],
	dir: string,
};

export type BundleFile = {
	/**  相对于插件根目录的路径（不允许 `..` 与绝对路径） */
	path: string,
	content: string,
	encoding?: FileEncoding,
};

/**
 *  插件声明的一项能力。
 * 
 *  serde 用 `kind` 做 tag，导出到 TS 就是可判别联合 ——
 *  前端可以直接 `switch (cap.kind)` 生成权限勾选界面，不需要额外映射表。
 */
export type Capability = 
/**  读文件 */
{ kind: "fsRead"; scope: PathScope } | 
/**  写文件 */
{ kind: "fsWrite"; scope: PathScope } | 
/**  出网。`hosts` 为空表示"任意主机"，非空则只允许这些主机（后缀匹配）。 */
{ kind: "net"; hosts: string[] } | 
/**  启动子进程 */
{ kind: "exec" } | 
/**  读取指定的环境变量（白名单，避免插件顺手把 API key 读走） */
{ kind: "env"; names: string[] } | 
/**  调用大模型服务（会计入用户额度） */
{ kind: "ai" } | 
/**  使用 GPU */
{ kind: "gpu" };

/**  草稿里的一个文件 */
export type DraftFile = {
	path: string,
	content: string,
	language: string,
};

/**
 *  引擎的**静态**描述（内置目录，不随运行状态变化）。
 * 
 *  `licenses` 字段是刻意保留的：FFmpeg（LGPL/GPL，编译选项决定）、
 *  LibreOffice（MPL-2.0）、Calibre（GPL-3.0）分发时各有约束，
 *  UI 需要在用户点"下载"之前就把这件事讲清楚。
 */
export type EngineDescriptor = EngineDescriptor_Serialize | EngineDescriptor_Deserialize;

/**
 *  引擎的**静态**描述（内置目录，不随运行状态变化）。
 * 
 *  `licenses` 字段是刻意保留的：FFmpeg（LGPL/GPL，编译选项决定）、
 *  LibreOffice（MPL-2.0）、Calibre（GPL-3.0）分发时各有约束，
 *  UI 需要在用户点"下载"之前就把这件事讲清楚。
 */
export type EngineDescriptor_Deserialize = {
	id: string,
	name: string,
	description: string,
	/**  官方主页 */
	homepage: string,
	/**  许可证标识 */
	license: string,
	/**  许可证注意事项（分发/商用时的坑） */
	licenseNote: string,
	/**  大致体积（MB），用于在 UI 上提前告知用户要下多少 */
	approxSizeMb: number,
	/**  是否是核心引擎 —— 缺失时应用能跑，但一部分内置节点不可用 */
	core: boolean,
	/**  该引擎提供的能力标签，与 [`crate::pipeline::NodeDescriptor::requires_engines`] 对应 */
	provides: string[],
	/**  支持的平台（`windows` / `macos` / `linux`） */
	platforms: string[],
	installModes: EngineInstallMode[],
	/**  是否需要在下载前让用户确认许可证 */
	requiresLicenseAck: boolean,
	/**  可选的模型权重（例如抠图的 U2Net），与主程序分开下载 */
	models: EngineModel_Deserialize[],
};

/**
 *  引擎的**静态**描述（内置目录，不随运行状态变化）。
 * 
 *  `licenses` 字段是刻意保留的：FFmpeg（LGPL/GPL，编译选项决定）、
 *  LibreOffice（MPL-2.0）、Calibre（GPL-3.0）分发时各有约束，
 *  UI 需要在用户点"下载"之前就把这件事讲清楚。
 */
export type EngineDescriptor_Serialize = {
	id: string,
	name: string,
	description: string,
	/**  官方主页 */
	homepage: string,
	/**  许可证标识 */
	license: string,
	/**  许可证注意事项（分发/商用时的坑） */
	licenseNote: string,
	/**  大致体积（MB），用于在 UI 上提前告知用户要下多少 */
	approxSizeMb: number,
	/**  是否是核心引擎 —— 缺失时应用能跑，但一部分内置节点不可用 */
	core: boolean,
	/**  该引擎提供的能力标签，与 [`crate::pipeline::NodeDescriptor::requires_engines`] 对应 */
	provides: string[],
	/**  支持的平台（`windows` / `macos` / `linux`） */
	platforms: string[],
	installModes: EngineInstallMode[],
	/**  是否需要在下载前让用户确认许可证 */
	requiresLicenseAck: boolean,
	/**  可选的模型权重（例如抠图的 U2Net），与主程序分开下载 */
	models: EngineModel_Serialize[],
};

/**  引擎目录项 = 静态描述 + 运行时状态。 */
export type EngineEntry = EngineEntry_Serialize | EngineEntry_Deserialize;

/**  引擎目录项 = 静态描述 + 运行时状态。 */
export type EngineEntry_Deserialize = {
	descriptor: EngineDescriptor_Deserialize,
	status: EngineStatus_Deserialize,
	/**  依赖这个引擎的内置节点名列表（UI 上显示"装了它能解锁什么"） */
	usedByNodes: string[],
	/**
	 *  当前平台是否配置了可下载的来源。
	 * 
	 *  界面靠它决定要不要显示「安装托管版本」—— 对一个没有下载源的引擎
	 *  （如 7-Zip、tesseract、calibre）显示这个按钮，用户点了只会得到一句
	 *  "当前平台没有配置下载源"，那是白白浪费一次点击。
	 */
	managedAvailable: boolean,
};

/**  引擎目录项 = 静态描述 + 运行时状态。 */
export type EngineEntry_Serialize = {
	descriptor: EngineDescriptor_Serialize,
	status: EngineStatus_Serialize,
	/**  依赖这个引擎的内置节点名列表（UI 上显示"装了它能解锁什么"） */
	usedByNodes: string[],
	/**
	 *  当前平台是否配置了可下载的来源。
	 * 
	 *  界面靠它决定要不要显示「安装托管版本」—— 对一个没有下载源的引擎
	 *  （如 7-Zip、tesseract、calibre）显示这个按钮，用户点了只会得到一句
	 *  "当前平台没有配置下载源"，那是白白浪费一次点击。
	 */
	managedAvailable: boolean,
};

/**  引擎的安装/获取方式 */
export type EngineInstallMode = 
/**  仅探测系统已安装 */
"system" | 
/**  由应用按需下载 */
"download" | 
/**  通过 pip 安装到插件私有 venv */
"pip" | 
/**  由外部大模型服务提供（无本地二进制） */
"remote";

/**  引擎安装请求。 */
export type EngineInstallRequest = {
	engineId: string,
	/**  用户是否已经确认了许可证条款 */
	licenseAccepted?: boolean,
	/**  是否允许安装没有 SHA-256 的来源（需要在 UI 上做二次确认） */
	allowUnverified?: boolean,
	/**
	 *  即使系统上已经有一个可用的，也强制安装**应用托管**的那一份。
	 * 
	 *  用在"系统上那个版本不满足要求"的场景：最典型的是 Python ——
	 *  系统装着 3.14 会被判为"已可用"，但抠图需要的 onnxruntime
	 *  没有 3.14 的 wheel，而托管版本固定 3.11。
	 */
	force?: boolean,
};

/**
 *  模型权重。**刻意与引擎本身分开** —— 权重体积大、许可证各异，
 *  而且很多是"只有用了这个功能才需要"。
 */
export type EngineModel = EngineModel_Serialize | EngineModel_Deserialize;

/**
 *  模型权重。**刻意与引擎本身分开** —— 权重体积大、许可证各异，
 *  而且很多是"只有用了这个功能才需要"。
 */
export type EngineModel_Deserialize = {
	id: string,
	name: string,
	/**  模型用途说明 */
	purpose: string,
	approxSizeMb: number,
	/**  权重许可证（可能与代码许可证不同！） */
	license: string,
	/**  是否允许商用 */
	commercialUse: boolean,
	/**  下载地址与校验值 */
	url?: string | null,
	/**
	 *  **备用下载地址**：主地址连不上时按顺序再试一个。
	 * 
	 *  # 为什么需要它（不是"多填一个地址保险一点"）
	 * 
	 *  这些权重的官方源是 `huggingface.co`，而它在**部分网络下不可达**
	 *  （本机实测：没开加速时 DNS/TCP 都不通，开了才 200）。社区镜像
	 *  `hf-mirror.com` 在同一网络下能用，但它是第三方、而且**会抖**。
	 * 
	 *  只填官方 → 那部分用户完全下不了；只填镜像 → 所有用户都依赖第三方。
	 *  两个都填，按"官方优先、镜像兜底"的顺序试，才是对两边都成立的答案。
	 * 
	 *  ⚠️ **必须与主地址是同一个文件**：每次下载都会核对 `sha256`，
	 *  不一致会被删掉并报 `INTEGRITY_CHECK_FAILED`。有一条测试
	 *  （`fallback_urls_point_at_the_same_asset`）强制它与主地址指向同一个资产名。
	 */
	fallbackUrl?: string | null,
	sha256?: string | null,
	/**
	 *  落盘文件名。
	 * 
	 *  单独一个字段是必需的：GitHub 上的资产名（`isnet-general-use.onnx`）
	 *  经常和模型 id（`isnet-general`）**对不上**。靠 `format!("{id}.onnx")`
	 *  猜文件名的话，下载成功、校验通过、然后"已安装"永远为假。
	 */
	fileName?: string | null,
	/**  该模型是否已下载（运行时填充） */
	installed?: boolean,
	/**
	 *  这个**权重**具体服务于哪些节点。
	 * 
	 *  为什么不能靠"它所属引擎被谁用"来推：`onnx-models` 这一个引擎同时承载
	 *  抠图和超分两组权重，于是在引擎粒度上算出来的结论是
	 *  "u2netp 被 `image.remove-background` 和 `ai.upscale` 共用" ——
	 *  那是**假的**。它造成的实际后果不是"界面上多显示一行"，而是：
	 *  一个验证脚本按"谁服务于 ai.upscale"去挑模型，挑中了 u2netp，
	 *  于是拿一个**分割模型**去超分，输出了垃圾 —— 而尺寸断言照样通过，
	 *  整条检查"全绿"。权重与节点的对应只能在权重这一层写清楚，推不出来。
	 */
	usedBy?: string[],
};

/**
 *  模型权重。**刻意与引擎本身分开** —— 权重体积大、许可证各异，
 *  而且很多是"只有用了这个功能才需要"。
 */
export type EngineModel_Serialize = {
	id: string,
	name: string,
	/**  模型用途说明 */
	purpose: string,
	approxSizeMb: number,
	/**  权重许可证（可能与代码许可证不同！） */
	license: string,
	/**  是否允许商用 */
	commercialUse: boolean,
	/**  下载地址与校验值 */
	url?: string | null,
	/**
	 *  **备用下载地址**：主地址连不上时按顺序再试一个。
	 * 
	 *  # 为什么需要它（不是"多填一个地址保险一点"）
	 * 
	 *  这些权重的官方源是 `huggingface.co`，而它在**部分网络下不可达**
	 *  （本机实测：没开加速时 DNS/TCP 都不通，开了才 200）。社区镜像
	 *  `hf-mirror.com` 在同一网络下能用，但它是第三方、而且**会抖**。
	 * 
	 *  只填官方 → 那部分用户完全下不了；只填镜像 → 所有用户都依赖第三方。
	 *  两个都填，按"官方优先、镜像兜底"的顺序试，才是对两边都成立的答案。
	 * 
	 *  ⚠️ **必须与主地址是同一个文件**：每次下载都会核对 `sha256`，
	 *  不一致会被删掉并报 `INTEGRITY_CHECK_FAILED`。有一条测试
	 *  （`fallback_urls_point_at_the_same_asset`）强制它与主地址指向同一个资产名。
	 */
	fallbackUrl?: string | null,
	sha256?: string | null,
	/**
	 *  落盘文件名。
	 * 
	 *  单独一个字段是必需的：GitHub 上的资产名（`isnet-general-use.onnx`）
	 *  经常和模型 id（`isnet-general`）**对不上**。靠 `format!("{id}.onnx")`
	 *  猜文件名的话，下载成功、校验通过、然后"已安装"永远为假。
	 */
	fileName?: string | null,
	/**  该模型是否已下载（运行时填充） */
	installed: boolean,
	/**
	 *  这个**权重**具体服务于哪些节点。
	 * 
	 *  为什么不能靠"它所属引擎被谁用"来推：`onnx-models` 这一个引擎同时承载
	 *  抠图和超分两组权重，于是在引擎粒度上算出来的结论是
	 *  "u2netp 被 `image.remove-background` 和 `ai.upscale` 共用" ——
	 *  那是**假的**。它造成的实际后果不是"界面上多显示一行"，而是：
	 *  一个验证脚本按"谁服务于 ai.upscale"去挑模型，挑中了 u2netp，
	 *  于是拿一个**分割模型**去超分，输出了垃圾 —— 而尺寸断言照样通过，
	 *  整条检查"全绿"。权重与节点的对应只能在权重这一层写清楚，推不出来。
	 */
	usedBy: string[],
};

/**  引擎来源 */
export type EngineSource = "none" | 
/**  系统 PATH / 注册表里找到的 */
"system" | 
/**  下载到应用数据目录的 */
"managed" | 
/**  随应用一起分发的 sidecar */
"sidecar" | "remote";

/**  引擎运行状态 */
export type EngineState = 
/**  未安装、也未探测到 */
"missing" | 
/**  检测到系统安装 */
"detected" | 
/**  由应用托管安装完成 */
"installed" | 
/**  正在安装/下载 */
"installing" | 
/**  安装或探测失败 */
"failed" | 
/**  版本低于最低要求 */
"outdated" | 
/**  该引擎在当前平台不受支持 */
"unsupported";

/**  引擎的**运行时**状态。 */
export type EngineStatus = EngineStatus_Serialize | EngineStatus_Deserialize;

/**  引擎的**运行时**状态。 */
export type EngineStatus_Deserialize = {
	id: string,
	state: EngineState,
	source: EngineSource,
	/**  可执行文件路径（System/Managed 时存在） */
	path?: string | null,
	/**  探测到的版本字符串 */
	version?: string | null,
	/**  状态说明 / 失败原因 / 安装指引 */
	message?: string | null,
	/**  已占用磁盘（MB） */
	installedSizeMb?: number | null,
	/**  已下载的模型 */
	installedModels?: string[],
	/**  最近一次探测时间（ISO-8601） */
	probedAt?: string | null,
};

/**  引擎的**运行时**状态。 */
export type EngineStatus_Serialize = {
	id: string,
	state: EngineState,
	source: EngineSource,
	/**  可执行文件路径（System/Managed 时存在） */
	path?: string | null,
	/**  探测到的版本字符串 */
	version?: string | null,
	/**  状态说明 / 失败原因 / 安装指引 */
	message?: string | null,
	/**  已占用磁盘（MB） */
	installedSizeMb?: number | null,
	/**  已下载的模型 */
	installedModels: string[],
	/**  最近一次探测时间（ISO-8601） */
	probedAt?: string | null,
};

/**  错误判别式。**新增值只能往后加，不要改已有值的语义** —— 前端会匹配它。 */
export type ErrorCode = 
/**  入参不合法 */
"INVALID_ARGUMENT" | 
/**  找不到文件 / 任务 / 插件 / 引擎 */
"NOT_FOUND" | 
/**  权限被拒绝（插件能力未授予、路径越权、沙箱拦截） */
"PERMISSION_DENIED" | 
/**  所需能力引擎未安装 */
"ENGINE_MISSING" | 
/**  引擎存在但调用失败 */
"ENGINE_FAILED" | 
/**  插件清单解析/校验失败 */
"PLUGIN_INVALID" | 
/**  插件运行时错误（WASM 陷阱、Python 崩溃） */
"PLUGIN_RUNTIME" | 
/**  插件使用了未声明的能力（**安全事件，会被审计记录**） */
"PLUGIN_CAPABILITY_VIOLATION" | 
/**  任务被取消 */
"CANCELLED" | 
/**  超时 */
"TIMEOUT" | 
/**  网络/下载失败 */
"NETWORK" | 
/**  哈希校验失败（下载产物被篡改或不完整） */
"INTEGRITY_CHECK_FAILED" | 
/**  AI 服务不可用或未配置 */
"AI_UNAVAILABLE" | 
/**  AI 产出未通过静态校验或安全审核 */
"AI_REJECTED" | 
/**  IO 错误 */
"IO" | 
/**  序列化/反序列化错误 */
"SERDE" | 
/**  兜底 */
"INTERNAL";

export type FileEncoding = "utf8" | 
/**  WASM 二进制走 base64，因为 JSON IPC 传不了裸字节 */
"base64";

/**  授权请求 */
export type GrantPermissionsRequest = {
	pluginId: string,
	granted: PermissionSet,
};

/**  安装插件的请求。 */
export type InstallPluginRequest = {
	source: PluginSource,
	/**  是否覆盖已存在的同名插件 */
	overwrite?: boolean,
	/**  用户是否已确认权限清单（L1/L2 必填；L3 需要额外确认可执行代码） */
	permissionsAcknowledged?: boolean,
	/**  仅 L3：用户是否确认"这是可执行代码" */
	executableCodeAcknowledged?: boolean,
};

/**  安装结果（前端用来展示"校验报告 + 权限清单 + 哈希"三重确认页） */
export type InstallReport = InstallReport_Serialize | InstallReport_Deserialize;

/**  安装结果（前端用来展示"校验报告 + 权限清单 + 哈希"三重确认页） */
export type InstallReport_Deserialize = {
	summary: PluginSummary_Deserialize,
	validation: ValidationReport_Deserialize,
	/**  内容哈希（`sha256:...`），展示在确认页上 */
	contentHash: string,
	/**  与已装旧版本相比**新增**的能力声明 —— 非空意味着必须重新人工确认 */
	addedCapabilities: string[],
	/**  与已装旧版本相比移除的能力 */
	removedCapabilities: string[],
	/**  落盘位置 */
	installPath: string,
};

/**  安装结果（前端用来展示"校验报告 + 权限清单 + 哈希"三重确认页） */
export type InstallReport_Serialize = {
	summary: PluginSummary_Serialize,
	validation: ValidationReport_Serialize,
	/**  内容哈希（`sha256:...`），展示在确认页上 */
	contentHash: string,
	/**  与已装旧版本相比**新增**的能力声明 —— 非空意味着必须重新人工确认 */
	addedCapabilities: string[],
	/**  与已装旧版本相比移除的能力 */
	removedCapabilities: string[],
	/**  落盘位置 */
	installPath: string,
};

export type IoPort = IoPort_Serialize | IoPort_Deserialize;

export type IoPort_Deserialize = {
	id: string,
	label: string,
	type: PortType,
	/**  MIME 或扩展名通配，例如 `["image/*", ".png"]`；空表示不限 */
	accept?: string[],
	multiple?: boolean,
	required?: boolean,
	description?: string | null,
};

export type IoPort_Serialize = {
	id: string,
	label: string,
	type: PortType,
	/**  MIME 或扩展名通配，例如 `["image/*", ".png"]`；空表示不限 */
	accept: string[],
	multiple: boolean,
	required: boolean,
	description?: string | null,
};

/**  一个任务。 */
export type Job = Job_Serialize | Job_Deserialize;

/**  任务过滤条件（前端任务中心用） */
export type JobFilter = JobFilter_Serialize | JobFilter_Deserialize;

/**  任务过滤条件（前端任务中心用） */
export type JobFilter_Deserialize = {
	statuses?: JobStatus[],
	kinds?: string[],
	search?: string | null,
	limit?: number | null,
};

/**  任务过滤条件（前端任务中心用） */
export type JobFilter_Serialize = {
	statuses: JobStatus[],
	kinds: string[],
	search?: string | null,
	limit?: number | null,
};

/** 任务 ID，例如 `job-9f3a12bc4d5e` */
export type JobId = string;

/**
 *  任务类别。前端据此决定图标、详情面板内容、以及是否能重试。
 * 
 *  ⚠️ `rename_all_fields` 不是可选项：枚举级的 `rename_all` 只改**变体名**，
 *  不改变体里的**字段名**。少了它，`PluginRun { plugin_id }` 会导出成
 *  `{ kind: "pluginRun", plugin_id: string }` —— 前端按 `pluginId` 取值就拿到
 *  `undefined`。生成绑定后请务必核对 `bindings.ts` 里的字段名。
 */
export type JobKind = 
/**  单文件/多文件格式转换 */
{ kind: "convert" } | 
/**  批量重命名 */
{ kind: "batchRename" } | 
/**  运行某个插件 */
{ kind: "pluginRun"; pluginId: string } | 
/**  运行一条可视化流水线 */
{ kind: "pipelineRun"; name: string } | 
/**  下载安装能力引擎 */
{ kind: "engineInstall"; engineId: string } | 
/**  下载模型权重 */
{ kind: "modelDownload"; modelId: string } | 
/**  AI 生成插件 */
{ kind: "aiGenerate"; provider: string } | 
/**  探测媒体信息 */
{ kind: "probe" } | 
/**  杂项（由标题说明） */
{ kind: "other"; label: string };

export type JobLogEntry = {
	/**  ISO-8601 */
	at: string,
	level: LogLevel,
	message: string,
};

export type JobProgress = JobProgress_Serialize | JobProgress_Deserialize;

export type JobProgress_Deserialize = {
	/**  0.0 ..= 1.0；未知总量时为 None（前端显示不确定进度条） */
	value?: number | null,
	/**  当前阶段的人类可读描述，例如"正在转码 第 3/10 个" */
	stage: string,
	/**  当前正在处理的文件 */
	currentItem?: string | null,
	/**  传输速率（下载任务用） */
	speed?: string | null,
	/**  预计剩余秒数 */
	etaSeconds?: number | null,
};

export type JobProgress_Serialize = {
	/**  0.0 ..= 1.0；未知总量时为 None（前端显示不确定进度条） */
	value?: number | null,
	/**  当前阶段的人类可读描述，例如"正在转码 第 3/10 个" */
	stage: string,
	/**  当前正在处理的文件 */
	currentItem?: string | null,
	/**  传输速率（下载任务用） */
	speed?: string | null,
	/**  预计剩余秒数 */
	etaSeconds?: number | null,
};

/**  任务状态统计（仪表盘用） */
export type JobStats = {
	byStatus: { [key in string]: number },
	total: number,
	succeeded: number,
	failed: number,
};

export type JobStatus = "queued" | "running" | "succeeded" | "failed" | "cancelled";

/**  一个任务。 */
export type Job_Deserialize = {
	id: JobId,
	kind: JobKind,
	title: string,
	status: JobStatus,
	progress: JobProgress_Deserialize,
	createdAt: string,
	startedAt?: string | null,
	finishedAt?: string | null,
	error?: ToolforgeError_Deserialize | null,
	/**  日志只保留尾部 N 条（见 [`Job::LOG_TAIL_LIMIT`]），避免长任务把内存吃光 */
	logs?: JobLogEntry[],
	/**  产出文件路径 */
	outputs?: string[],
	/**  总条目数 / 已完成 / 失败（批量任务用） */
	totalItems?: number,
	completedItems?: number,
	failedItems?: number,
};

/**  一个任务。 */
export type Job_Serialize = {
	id: JobId,
	kind: JobKind,
	title: string,
	status: JobStatus,
	progress: JobProgress_Serialize,
	createdAt: string,
	startedAt?: string | null,
	finishedAt?: string | null,
	error?: ToolforgeError_Serialize | null,
	/**  日志只保留尾部 N 条（见 [`Job::LOG_TAIL_LIMIT`]），避免长任务把内存吃光 */
	logs: JobLogEntry[],
	/**  产出文件路径 */
	outputs: string[],
	/**  总条目数 / 已完成 / 失败（批量任务用） */
	totalItems: number,
	completedItems: number,
	failedItems: number,
};

/**  统一的 `jobs_list` 请求（specta 对 `Option<JobFilter>` 的处理不如显式结构体清晰） */
export type JobsListRequest = JobsListRequest_Serialize | JobsListRequest_Deserialize;

/**  统一的 `jobs_list` 请求（specta 对 `Option<JobFilter>` 的处理不如显式结构体清晰） */
export type JobsListRequest_Deserialize = {
	filter?: JobFilter_Deserialize,
};

/**  统一的 `jobs_list` 请求（specta 对 `Option<JobFilter>` 的处理不如显式结构体清晰） */
export type JobsListRequest_Serialize = {
	filter: JobFilter_Serialize,
};

export type JobsSnapshot = JobsSnapshot_Serialize | JobsSnapshot_Deserialize;

export type JobsSnapshot_Deserialize = {
	jobs: Job_Deserialize[],
	activeCount: number,
	running: string[],
};

export type JobsSnapshot_Serialize = {
	jobs: Job_Serialize[],
	activeCount: number,
	running: string[],
};

export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";

/**
 *  一个模型权重的完整状态 = 静态描述 + 是否已下载 + 谁需要它。
 * 
 *  为什么不直接把 `EngineModel` 发给前端：那个结构里没有"能不能下载"
 *  （`url` / `sha256` 是否齐全）这个**用户最关心**的字段 ——
 *  缺下载源的模型点"下载"必然失败，界面必须提前把按钮禁掉并说明原因。
 */
export type ModelEntry = ModelEntry_Serialize | ModelEntry_Deserialize;

/**
 *  一个模型权重的完整状态 = 静态描述 + 是否已下载 + 谁需要它。
 * 
 *  为什么不直接把 `EngineModel` 发给前端：那个结构里没有"能不能下载"
 *  （`url` / `sha256` 是否齐全）这个**用户最关心**的字段 ——
 *  缺下载源的模型点"下载"必然失败，界面必须提前把按钮禁掉并说明原因。
 */
export type ModelEntry_Deserialize = {
	id: string,
	name: string,
	purpose: string,
	license: string,
	commercialUse: boolean,
	/**  估算体积（MB），用于"要不要现在下"的判断 */
	approxSizeMb: number,
	/**  是否已经下载到本机 */
	installed: boolean,
	/**  已落盘的实际大小（MB）；未安装时为 `None` */
	installedSizeMb?: number | null,
	/**  是否配置了可校验的下载源。`false` 时界面应禁用下载并说明原因。 */
	downloadable: boolean,
	/**  依赖这个模型的节点名 */
	usedByNodes: string[],
	/**  模型所属的引擎（通常是虚拟引擎 `onnx-models`） */
	engineId: string,
};

/**
 *  一个模型权重的完整状态 = 静态描述 + 是否已下载 + 谁需要它。
 * 
 *  为什么不直接把 `EngineModel` 发给前端：那个结构里没有"能不能下载"
 *  （`url` / `sha256` 是否齐全）这个**用户最关心**的字段 ——
 *  缺下载源的模型点"下载"必然失败，界面必须提前把按钮禁掉并说明原因。
 */
export type ModelEntry_Serialize = {
	id: string,
	name: string,
	purpose: string,
	license: string,
	commercialUse: boolean,
	/**  估算体积（MB），用于"要不要现在下"的判断 */
	approxSizeMb: number,
	/**  是否已经下载到本机 */
	installed: boolean,
	/**  已落盘的实际大小（MB）；未安装时为 `None` */
	installedSizeMb?: number | null,
	/**  是否配置了可校验的下载源。`false` 时界面应禁用下载并说明原因。 */
	downloadable: boolean,
	/**  依赖这个模型的节点名 */
	usedByNodes: string[],
	/**  模型所属的引擎（通常是虚拟引擎 `onnx-models`） */
	engineId: string,
};

/**  模型下载请求。 */
export type ModelInstallRequest = {
	modelId: string,
	/**  用户是否已确认该权重的许可证（部分权重不允许商用） */
	licenseAccepted?: boolean,
};

/**  内置节点目录（流程编辑器的节点面板） */
export type NodeCatalogResponse = NodeCatalogResponse_Serialize | NodeCatalogResponse_Deserialize;

/**  内置节点目录（流程编辑器的节点面板） */
export type NodeCatalogResponse_Deserialize = {
	nodes: NodeDescriptor_Deserialize[],
	/**  当前各节点的可用性（引擎缺失时置 false） */
	availability: { [key in string]: boolean },
	/**  缺失引擎 -> 需要它的节点 */
	missingEngines: { [key in string]: string[] },
	/**
	 *  **尚未实现执行器**的节点名。
	 * 
	 *  ⚠️ 前端**不要**再硬编这份名单 —— 它来自
	 *  `toolforge_core::pipeline::UNIMPLEMENTED_NODES`（唯一真相来源），
	 *  由 `unimplemented_list_matches_actual_dispatch` 与
	 *  `is_implemented_is_the_complement_of_the_list` 两条测试守着。
	 * 
	 *  这份名单曾经在四个地方各存了一份（Rust 执行器、SDK 文档、示例清单注释、
	 *  前端的 `node-support.ts`），每实现一个节点就要手工同步四处。
	 *  漏掉任何一处，用户就会看到与实际行为相反的提示。
	 */
	unimplemented: string[],
};

/**  内置节点目录（流程编辑器的节点面板） */
export type NodeCatalogResponse_Serialize = {
	nodes: NodeDescriptor_Serialize[],
	/**  当前各节点的可用性（引擎缺失时置 false） */
	availability: { [key in string]: boolean },
	/**  缺失引擎 -> 需要它的节点 */
	missingEngines: { [key in string]: string[] },
	/**
	 *  **尚未实现执行器**的节点名。
	 * 
	 *  ⚠️ 前端**不要**再硬编这份名单 —— 它来自
	 *  `toolforge_core::pipeline::UNIMPLEMENTED_NODES`（唯一真相来源），
	 *  由 `unimplemented_list_matches_actual_dispatch` 与
	 *  `is_implemented_is_the_complement_of_the_list` 两条测试守着。
	 * 
	 *  这份名单曾经在四个地方各存了一份（Rust 执行器、SDK 文档、示例清单注释、
	 *  前端的 `node-support.ts`），每实现一个节点就要手工同步四处。
	 *  漏掉任何一处，用户就会看到与实际行为相反的提示。
	 */
	unimplemented: string[],
};

export type NodeCategory = "file" | "image" | "video" | "audio" | "document" | "archive" | "ebook" | "text" | "ai" | "flow";

/**  一个内置节点的元描述。流程编辑器的节点面板、参数表单、引擎缺失提示全部由它驱动。 */
export type NodeDescriptor = NodeDescriptor_Serialize | NodeDescriptor_Deserialize;

/**  一个内置节点的元描述。流程编辑器的节点面板、参数表单、引擎缺失提示全部由它驱动。 */
export type NodeDescriptor_Deserialize = {
	/**  全名，插件清单里 `uses` 就是它 */
	name: string,
	label: string,
	description: string,
	category: NodeCategory,
	/**  必需引擎：缺失则该节点不可用（UI 里显示"需要安装 FFmpeg"） */
	requiresEngines: string[],
	/**  可选引擎：缺失时自动降级，功能仍在 */
	optionalEngines: string[],
	inputs: IoPort_Deserialize[],
	outputs: IoPort_Deserialize[],
	params: ParamSpec_Deserialize[],
};

/**  一个内置节点的元描述。流程编辑器的节点面板、参数表单、引擎缺失提示全部由它驱动。 */
export type NodeDescriptor_Serialize = {
	/**  全名，插件清单里 `uses` 就是它 */
	name: string,
	label: string,
	description: string,
	category: NodeCategory,
	/**  必需引擎：缺失则该节点不可用（UI 里显示"需要安装 FFmpeg"） */
	requiresEngines: string[],
	/**  可选引擎：缺失时自动降级，功能仍在 */
	optionalEngines: string[],
	inputs: IoPort_Serialize[],
	outputs: IoPort_Serialize[],
	params: ParamSpec_Serialize[],
};

export type OnErrorPolicy = 
/**  中止整个任务（默认） */
"fail" | 
/**  跳过该步继续 */
"skip" | 
/**  跳过该步，并把失败原因写入 `${steps.<id>.error}` */
"continue" | 
/**  重试 N 次后仍然失败则中止 */
"retry";

export type ParamOption = {
	value: string,
	label: string,
};

export type ParamSpec = ParamSpec_Serialize | ParamSpec_Deserialize;

export type ParamSpec_Deserialize = {
	id: string,
	label: string,
	type: ParamType,
	description?: string | null,
	default?: ParamValue | null,
	/**  `enum` 类型的候选值 */
	options?: ParamOption[],
	min?: number | null,
	max?: number | null,
	step?: number | null,
	required?: boolean,
	placeholder?: string | null,
	/**  文本参数是否用多行输入框 */
	multiline?: boolean,
	/**  该参数变化时是否需要重新探测输入（用于 UI 联动） */
	affectsOutput?: boolean,
};

export type ParamSpec_Serialize = {
	id: string,
	label: string,
	type: ParamType,
	description?: string | null,
	default?: ParamValue | null,
	/**  `enum` 类型的候选值 */
	options: ParamOption[],
	min?: number | null,
	max?: number | null,
	step?: number | null,
	required: boolean,
	placeholder?: string | null,
	/**  文本参数是否用多行输入框 */
	multiline: boolean,
	/**  该参数变化时是否需要重新探测输入（用于 UI 联动） */
	affectsOutput: boolean,
};

export type ParamType = "text" | "textarea" | "int" | "float" | "bool" | "enum" | 
/**  多选枚举 */
"multiEnum" | 
/**  用户选择文件/目录（由宿主弹原生对话框，插件拿到的是逻辑路径） */
"path" | "directory" | "color" | 
/**  逗号分隔的键值对，例如 `-vf scale=1280:-1` */
"keyValue";

/**
 *  参数取值。刻意不用 `serde_json::Value` —— 显式枚举能让 specta 导出成
 *  TS 可判别联合，前端做表单绑定时不需要 `any`。
 */
export type ParamValue = { kind: "str"; value: string } | { kind: "int"; value: number } | { kind: "float"; value: number | null } | { kind: "bool"; value: boolean } | { kind: "list"; value: string[] };

export type PathEntry = {
	label: string,
	path: string,
};

/**  插件可引用的**逻辑**路径作用域。插件拿不到真实绝对路径。 */
export type PathScope = 
/**  本次任务的输入文件所在目录（宿主自动加入，只读） */
{ kind: "input" } | 
/**  用户为本次任务指定的输出目录 */
{ kind: "output" } | 
/**  插件私有持久化目录（跨任务保留，例如模型缓存、配置） */
{ kind: "pluginData" } | 
/**  本次任务的临时目录，任务结束后由宿主清理 */
{ kind: "workspace" } | 
/**
 *  显式声明的宿主机路径 glob。
 * 
 *  **这是逃生舱口，风险等级直接拉到 Critical**，UI 会用红色警示并要求二次确认。
 *  只有确实需要访问固定系统目录（如 `%APPDATA%\SomeVendor`）时才应该用它。
 * 
 *  注意这里用的是**结构体变体**而不是 `Explicit(String)`：因为整个枚举是
 *  内部标签（`#[serde(tag = "kind")]`）表示，而 serde 与 specta 都不允许
 *  内部标签与 newtype 变体共存（primitive 载荷无法与 tag 合并）。
 */
{ kind: "explicit"; pattern: string };

/**
 *  一组能力声明。插件清单里的 `permissions` 和用户实际授予的集合都用它表示。
 * 
 *  ⚠️ 这里**刻意不加** `#[serde(transparent)]`：加了之后 YAML 会变成
 *  `permissions: [ ... ]` 这种裸数组，既不好读也没法在未来扩展字段。
 *  现在的形状是 `permissions: { capabilities: [ ... ] }`，
 *  所有示例插件与文档都按这个形状写。
 */
export type PermissionSet = {
	capabilities: Capability[],
};

export type PipelineDef = PipelineDef_Serialize | PipelineDef_Deserialize;

export type PipelineDef_Deserialize = {
	/**  可选的人类可读描述（流程编辑器里显示在节点上） */
	description?: string | null,
	steps: PipelineStep_Deserialize[],
	/**  单步失败时的整体策略 */
	onError?: OnErrorPolicy,
	/**  整个流水线的超时（毫秒），0 表示不限 */
	timeoutMs?: number,
};

export type PipelineDef_Serialize = {
	/**  可选的人类可读描述（流程编辑器里显示在节点上） */
	description?: string | null,
	steps: PipelineStep_Serialize[],
	/**  单步失败时的整体策略 */
	onError: OnErrorPolicy,
	/**  整个流水线的超时（毫秒），0 表示不限 */
	timeoutMs: number,
};

export type PipelineStep = PipelineStep_Serialize | PipelineStep_Deserialize;

export type PipelineStep_Deserialize = {
	/**  步骤 ID，在流水线内唯一；`${steps.<id>.*}` 引用它 */
	id: string,
	/**  内置节点名，必须存在于 [`builtin_nodes`] 里 */
	uses: string,
	/**  参数模板 */
	with?: { [key in string]: string },
	/**  人类可读标签（流程编辑器节点标题） */
	label?: string | null,
	/**  跳过条件：`${params.mode} != "fast"` 这类简单比较 */
	when?: string | null,
	/**  覆盖流水线级策略 */
	onError?: OnErrorPolicy | null,
	retry?: number,
	timeoutMs?: number | null,
	/**  流程编辑器里的画布坐标（由前端写回，宿主不解释） */
	position?: StepPosition | null,
	/**  依赖的步骤 id（流程编辑器画连线用；为空表示按声明顺序串行） */
	dependsOn?: string[],
};

export type PipelineStep_Serialize = {
	/**  步骤 ID，在流水线内唯一；`${steps.<id>.*}` 引用它 */
	id: string,
	/**  内置节点名，必须存在于 [`builtin_nodes`] 里 */
	uses: string,
	/**  参数模板 */
	with: { [key in string]: string },
	/**  人类可读标签（流程编辑器节点标题） */
	label?: string | null,
	/**  跳过条件：`${params.mode} != "fast"` 这类简单比较 */
	when?: string | null,
	/**  覆盖流水线级策略 */
	onError?: OnErrorPolicy | null,
	retry: number,
	timeoutMs?: number | null,
	/**  流程编辑器里的画布坐标（由前端写回，宿主不解释） */
	position?: StepPosition | null,
	/**  依赖的步骤 id（流程编辑器画连线用；为空表示按声明顺序串行） */
	dependsOn: string[],
};

export type PluginCategory = "image" | "audio" | "video" | "document" | "archive" | "ebook" | "text" | "dev" | "ai" | "system" | "other";

/**  插件详情（点开卡片后加载） */
export type PluginDetail = PluginDetail_Serialize | PluginDetail_Deserialize;

/**  插件详情（点开卡片后加载） */
export type PluginDetail_Deserialize = {
	summary: PluginSummary_Deserialize,
	manifest: PluginManifest_Deserialize,
	rawYaml: string,
	/**  用户实际授予的能力 */
	granted: PermissionSet,
	/**  插件目录下的文件列表（相对路径） */
	files: string[],
	readme?: string | null,
	/**  运行时健康状态（L2/L3 才有意义） */
	runtimeStatus?: string | null,
};

/**  插件详情（点开卡片后加载） */
export type PluginDetail_Serialize = {
	summary: PluginSummary_Serialize,
	manifest: PluginManifest_Serialize,
	rawYaml: string,
	/**  用户实际授予的能力 */
	granted: PermissionSet,
	/**  插件目录下的文件列表（相对路径） */
	files: string[],
	readme?: string | null,
	/**  运行时健康状态（L2/L3 才有意义） */
	runtimeStatus?: string | null,
};

export type PluginIo = PluginIo_Serialize | PluginIo_Deserialize;

export type PluginIo_Deserialize = {
	/**  数据输入端口（流程编辑器里画在左侧的连接点） */
	inputs?: IoPort_Deserialize[],
	/**  数据输出端口（右侧连接点） */
	outputs?: IoPort_Deserialize[],
	/**  用户可调参数（UI 自动生成表单） */
	params?: ParamSpec_Deserialize[],
};

export type PluginIo_Serialize = {
	/**  数据输入端口（流程编辑器里画在左侧的连接点） */
	inputs: IoPort_Serialize[],
	/**  数据输出端口（右侧连接点） */
	outputs: IoPort_Serialize[],
	/**  用户可调参数（UI 自动生成表单） */
	params: ParamSpec_Serialize[],
};

/**  插件清单根结构（`plugin.yaml`） */
export type PluginManifest = PluginManifest_Serialize | PluginManifest_Deserialize;

/**  插件清单根结构（`plugin.yaml`） */
export type PluginManifest_Deserialize = {
	/**  必须等于 [`crate::PLUGIN_API_VERSION`] */
	apiVersion: string,
	/**  固定为 `Plugin` */
	kind: string,
	metadata: PluginMetadata_Deserialize,
	/**  能力声明。**声明不等于授权**，见 `permission` 模块文档。 */
	permissions?: PermissionSet,
	io?: PluginIo_Deserialize,
	runtime: PluginRuntime_Deserialize,
	/**  AI 生成溯源信息。人工手写的插件此字段为 `None`。 */
	ai?: AiProvenance_Deserialize | null,
};

/**  插件清单根结构（`plugin.yaml`） */
export type PluginManifest_Serialize = {
	/**  必须等于 [`crate::PLUGIN_API_VERSION`] */
	apiVersion: string,
	/**  固定为 `Plugin` */
	kind: string,
	metadata: PluginMetadata_Serialize,
	/**  能力声明。**声明不等于授权**，见 `permission` 模块文档。 */
	permissions: PermissionSet,
	io: PluginIo_Serialize,
	runtime: PluginRuntime_Serialize,
	/**  AI 生成溯源信息。人工手写的插件此字段为 `None`。 */
	ai?: AiProvenance_Serialize | null,
};

export type PluginMetadata = PluginMetadata_Serialize | PluginMetadata_Deserialize;

export type PluginMetadata_Deserialize = {
	/**  全局唯一，建议反向域名，例如 `com.toolforge.builtin.image-convert` */
	id: string,
	name: string,
	version: string,
	description?: string | null,
	author?: string | null,
	license?: string | null,
	/**  Lucide 图标名 */
	icon?: string | null,
	category?: PluginCategory,
	tags?: string[],
	homepage?: string | null,
};

export type PluginMetadata_Serialize = {
	/**  全局唯一，建议反向域名，例如 `com.toolforge.builtin.image-convert` */
	id: string,
	name: string,
	version: string,
	description?: string | null,
	author?: string | null,
	license?: string | null,
	/**  Lucide 图标名 */
	icon?: string | null,
	category: PluginCategory,
	tags: string[],
	homepage?: string | null,
};

export type PluginRuntime = PluginRuntime_Serialize | PluginRuntime_Deserialize;

export type PluginRuntime_Deserialize = 
/**  L1：YAML 声明式编排，零代码 */
({ kind: "pipeline"; pipeline: PipelineDef_Deserialize }) & { python?: never; wasm?: never } | 
/**  L2：Extism WASM 沙箱，纯计算 */
({ kind: "wasm"; wasm: WasmRuntimeDef }) & { pipeline?: never; python?: never } | 
/**  L3：Python 独立进程 + JSON-RPC over stdio */
({ kind: "python"; python: PythonRuntimeDef }) & { pipeline?: never; wasm?: never };

export type PluginRuntime_Serialize = 
/**  L1：YAML 声明式编排，零代码 */
({ kind: "pipeline"; pipeline: PipelineDef_Serialize }) & { python?: never; wasm?: never } | 
/**  L2：Extism WASM 沙箱，纯计算 */
({ kind: "wasm"; wasm: WasmRuntimeDef }) & { pipeline?: never; python?: never } | 
/**  L3：Python 独立进程 + JSON-RPC over stdio */
({ kind: "python"; python: PythonRuntimeDef }) & { pipeline?: never; wasm?: never };

/**  插件安装来源。 */
export type PluginSource = 
/**  已存在于磁盘的插件目录 */
{ kind: "directory"; path: string } | 
/**  单个 YAML 清单（L1 插件，无需额外文件） */
{ kind: "manifest"; yaml: string } | 
/**  多文件包 —— AI 生成的插件从这里落盘 */
{ kind: "bundle"; yaml: string; files: BundleFile[] };

/**
 *  插件列表项。字段刻意冗余（把 UI 需要的都算好），避免前端为了渲染一个卡片
 *  再去拉详情。
 */
export type PluginSummary = PluginSummary_Serialize | PluginSummary_Deserialize;

/**
 *  插件列表项。字段刻意冗余（把 UI 需要的都算好），避免前端为了渲染一个卡片
 *  再去拉详情。
 */
export type PluginSummary_Deserialize = {
	id: string,
	name: string,
	version: string,
	description?: string | null,
	icon?: string | null,
	category: PluginCategory,
	tags: string[],
	runtimeKind: RuntimeKind,
	/**  是否已启用 */
	enabled: boolean,
	/**  是否随应用内置 */
	builtin: boolean,
	/**  是否由 AI 生成（UI 会打特殊标记） */
	aiGenerated: boolean,
	/**  是否已被用户审核确认过 */
	reviewed: boolean,
	riskLevel: RiskLevel,
	permissionCount: number,
	grantedCount: number,
	/**  是否存在未授权的声明能力（UI 提示"存在待授权项"） */
	hasPendingPermissions: boolean,
	installPath?: string | null,
};

/**
 *  插件列表项。字段刻意冗余（把 UI 需要的都算好），避免前端为了渲染一个卡片
 *  再去拉详情。
 */
export type PluginSummary_Serialize = {
	id: string,
	name: string,
	version: string,
	description?: string | null,
	icon?: string | null,
	category: PluginCategory,
	tags: string[],
	runtimeKind: RuntimeKind,
	/**  是否已启用 */
	enabled: boolean,
	/**  是否随应用内置 */
	builtin: boolean,
	/**  是否由 AI 生成（UI 会打特殊标记） */
	aiGenerated: boolean,
	/**  是否已被用户审核确认过 */
	reviewed: boolean,
	riskLevel: RiskLevel,
	permissionCount: number,
	grantedCount: number,
	/**  是否存在未授权的声明能力（UI 提示"存在待授权项"） */
	hasPendingPermissions: boolean,
	installPath?: string | null,
};

export type PluginsSnapshot = PluginsSnapshot_Serialize | PluginsSnapshot_Deserialize;

export type PluginsSnapshot_Deserialize = {
	plugins: PluginSummary_Deserialize[],
	/**  有未授权项的插件数（侧边栏红点） */
	pendingPermissionCount: number,
	/**  审计目录（安全页展示） */
	auditDir: string,
};

export type PluginsSnapshot_Serialize = {
	plugins: PluginSummary_Serialize[],
	/**  有未授权项的插件数（侧边栏红点） */
	pendingPermissionCount: number,
	/**  审计目录（安全页展示） */
	auditDir: string,
};

export type PortType = "file" | "files" | "directory" | "text" | "number" | "boolean" | "json" | 
/**  任意类型（流程编辑器里用虚线连接） */
"any";

export type PythonRuntimeDef = {
	/**  入口脚本，相对于插件目录 */
	entry: string,
	/**  期望的 Python 版本（宿主用它挑选 sidecar 运行时） */
	pythonVersion?: string,
	/**  pip 依赖，首次运行时由宿主在**插件独立的 venv** 里安装 */
	requirements?: string[],
	timeoutMs?: number,
	/**  进程数（模型加载很贵时 >1 才有意义；一般 1 个常驻进程即可） */
	workers?: number,
	/**  是否允许该进程出网。**默认 false**，需要走 [`PermissionSet`] 里的 Net 能力显式授权。 */
	allowNetwork?: boolean,
};

/**  审核发现 */
export type ReviewFinding = ReviewFinding_Serialize | ReviewFinding_Deserialize;

/**  审核发现 */
export type ReviewFinding_Deserialize = {
	severity: RiskLevel,
	/**  稳定标识，前端可据此做特殊展示 */
	code: string,
	message: string,
	/**  代码片段或字段路径 */
	evidence?: string | null,
};

/**  审核发现 */
export type ReviewFinding_Serialize = {
	severity: RiskLevel,
	/**  稳定标识，前端可据此做特殊展示 */
	code: string,
	message: string,
	/**  代码片段或字段路径 */
	evidence?: string | null,
};

/**  风险等级 */
export type RiskLevel = "low" | "medium" | "high" | "critical";

/**  插件运行请求。 */
export type RunPluginRequest = {
	pluginId: string,
	/**  输入端口的实际文件路径（由原生文件对话框或拖拽得到） */
	inputs: { [key in string]: string[] },
	params?: { [key in string]: ParamValue },
	/**  输出目录；空则用设置里的默认值 */
	outputDir?: string,
};

export type RunPluginResponse = {
	/**  立即返回任务 id，实际执行在队列里进行（前端订阅事件跟进度） */
	jobId: string,
	pluginName: string,
	/**  预计处理的文件总数 */
	totalItems: number,
};

export type RuntimeKind = "pipeline" | "wasm" | "python";

/**  审核报告 */
export type SecurityReview = SecurityReview_Serialize | SecurityReview_Deserialize;

/**  审核报告 */
export type SecurityReview_Deserialize = {
	/**  清单能否被解析 */
	parseable: boolean,
	/**  静态校验报告（错误码与 CLI 校验器一致） */
	validation: ValidationReport_Deserialize | null,
	/**  解析失败时的原因 */
	parseError?: string | null,
	/**  整体风险等级 = 所有发现里最高的那一档 */
	riskLevel: RiskLevel,
	/**  逐条发现 */
	findings: ReviewFinding_Deserialize[],
	/**  **是否建议放行到"用户确认"环节**。注意：为 true 也不代表可以直接装。 */
	recommended: boolean,
	/**  运行时摘要，展示在确认页顶部 */
	runtimeSummary?: string | null,
	/**  需要用户逐条勾选的能力（中文描述） */
	capabilities: string[],
};

/**  审核报告 */
export type SecurityReview_Serialize = {
	/**  清单能否被解析 */
	parseable: boolean,
	/**  静态校验报告（错误码与 CLI 校验器一致） */
	validation: ValidationReport_Serialize | null,
	/**  解析失败时的原因 */
	parseError?: string | null,
	/**  整体风险等级 = 所有发现里最高的那一档 */
	riskLevel: RiskLevel,
	/**  逐条发现 */
	findings: ReviewFinding_Serialize[],
	/**  **是否建议放行到"用户确认"环节**。注意：为 true 也不代表可以直接装。 */
	recommended: boolean,
	/**  运行时摘要，展示在确认页顶部 */
	runtimeSummary?: string | null,
	/**  需要用户逐条勾选的能力（中文描述） */
	capabilities: string[],
};

/**
 *  用户设置。全部字段都有默认值 —— 首次启动时不需要用户填任何东西。
 * 
 *  `#[serde(default)]` 挂在结构体上（而不是逐字段挂）是**向后兼容的关键**：
 *  以后新增字段时，老版本写下的 `settings.json` 照样能读出来，
 *  缺的字段用默认值补，而不是让整份设置解析失败。
 */
export type Settings = {
	/**  任务队列并发度 */
	concurrency?: number,
	/**  主题：`system` / `light` / `dark` */
	theme?: string,
	/**  强调色（CSS 变量注入） */
	accent?: string,
	/**  是否启用背景氛围动效（低配机器可关） */
	ambientEffects?: boolean,
	/**  默认输出目录；空表示"与源文件同目录" */
	defaultOutputDir?: string,
	/**  批量处理时是否保留源文件 */
	keepOriginal?: boolean,
	/**  AI 配置（不含 Key —— Key 在这个结构体之外，见 [`AiSettings::persist_api_key`]） */
	ai?: AiSettings,
	/**  启动时自动重新探测引擎 */
	probeEnginesOnStartup?: boolean,
};

/**  局部更新设置（`None` 表示不改这个字段）。 */
export type SettingsPatch = SettingsPatch_Serialize | SettingsPatch_Deserialize;

/**  局部更新设置（`None` 表示不改这个字段）。 */
export type SettingsPatch_Deserialize = {
	concurrency?: number | null,
	theme?: string | null,
	accent?: string | null,
	ambientEffects?: boolean | null,
	defaultOutputDir?: string | null,
	keepOriginal?: boolean | null,
	ai?: AiSettings | null,
	/**  写 `Some` 时会更新内存中的 Key；写 `Some("")` 则清除 */
	aiApiKey?: string | null,
	probeEnginesOnStartup?: boolean | null,
};

/**  局部更新设置（`None` 表示不改这个字段）。 */
export type SettingsPatch_Serialize = {
	concurrency?: number | null,
	theme?: string | null,
	accent?: string | null,
	ambientEffects?: boolean | null,
	defaultOutputDir?: string | null,
	keepOriginal?: boolean | null,
	ai?: AiSettings | null,
	/**  写 `Some` 时会更新内存中的 Key；写 `Some("")` 则清除 */
	aiApiKey?: string | null,
	probeEnginesOnStartup?: boolean | null,
};

export type Severity = "error" | "warning" | "info";

export type StepPosition = {
	x: number | null,
	y: number | null,
};

export type SystemStatus = {
	info: AppInfo,
	paths: AppPathsDto,
	/**  已可用引擎数 / 总数 */
	enginesReady: number,
	enginesTotal: number,
	/**  已装载的插件数 */
	pluginsTotal: number,
	pluginsEnabled: number,
	activeJobs: number,
	/**  数据库/目录是否可写 */
	storageWritable: boolean,
	/**  当前平台 */
	platform: string,
	/**  命令总数（开发信息） */
	commandCount: number,
};

/**  ToolForge 统一错误。 */
export type ToolforgeError = ToolforgeError_Serialize | ToolforgeError_Deserialize;

/**  ToolForge 统一错误。 */
export type ToolforgeError_Deserialize = {
	code: ErrorCode,
	message: string,
	/**  技术细节：stderr 尾部、引擎原始输出、校验器逐条问题等 */
	detail?: string | null,
	/**  出错时正在处理哪个任务 / 插件（便于前端定位） */
	subject?: string | null,
};

/**  ToolForge 统一错误。 */
export type ToolforgeError_Serialize = {
	code: ErrorCode,
	message: string,
	/**  技术细节：stderr 尾部、引擎原始输出、校验器逐条问题等 */
	detail?: string | null,
	/**  出错时正在处理哪个任务 / 插件（便于前端定位） */
	subject?: string | null,
};

/**  校验一份插件来源（不落盘）。用于"导入前先看看"。 */
export type ValidatePluginRequest = {
	source: PluginSource,
};

export type ValidatePluginResponse = ValidatePluginResponse_Serialize | ValidatePluginResponse_Deserialize;

export type ValidatePluginResponse_Deserialize = {
	validation: ValidationReport_Deserialize,
	/**  申请的能力（中文描述 + 风险等级） */
	capabilities: Capability[],
	/**  声明需要的引擎 */
	requiredEngines: string[],
	/**  缺失的引擎 */
	missingEngines: string[],
};

export type ValidatePluginResponse_Serialize = {
	validation: ValidationReport_Serialize,
	/**  申请的能力（中文描述 + 风险等级） */
	capabilities: Capability[],
	/**  声明需要的引擎 */
	requiredEngines: string[],
	/**  缺失的引擎 */
	missingEngines: string[],
};

export type ValidationIssue = ValidationIssue_Serialize | ValidationIssue_Deserialize;

export type ValidationIssue_Deserialize = {
	severity: Severity,
	code: string,
	message: string,
	path?: string | null,
};

export type ValidationIssue_Serialize = {
	severity: Severity,
	code: string,
	message: string,
	path?: string | null,
};

export type ValidationReport = ValidationReport_Serialize | ValidationReport_Deserialize;

export type ValidationReport_Deserialize = {
	ok: boolean,
	issues: ValidationIssue_Deserialize[],
};

export type ValidationReport_Serialize = {
	ok: boolean,
	issues: ValidationIssue_Serialize[],
};

export type WasmRuntimeDef = {
	/**  相对于插件目录的 wasm 文件名 */
	path: string,
	/**  导出函数名 */
	entry?: string,
	/**  内存上限（MB） */
	memoryLimitMb?: number,
	/**  单次调用超时（毫秒）。WASM 是纯计算，超时说明插件写挂了。 */
	timeoutMs?: number,
	/**
	 *  允许调用的宿主函数白名单。**默认空 = 完全沙箱，不能碰任何宿主资源。**
	 *  可选项只有 `"log"` 和 `"kv"`（插件私有键值存储）。
	 */
	allowHostFunctions?: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

