/**
 * # 领域类型：**唯一真相来源是 `src/bindings.ts`**
 *
 * 这个文件现在只是一层**薄薄的别名层**，不再自己定义任何镜像 Rust 的结构：
 *
 * ```text
 * Rust 类型 ──(tauri-specta / pnpm bindings)──► src/bindings.ts ──► 本文件的别名
 * ```
 *
 * 为什么这么做：手写一份"镜像类型"意味着**两套真相**。后端改一个字段名，
 * 手写这份照旧编译通过，运行时才炸 —— 而且是在用户点下按钮之后才炸。
 * 生成的 bindings 是从真实 Rust 类型导出的，字段名/可选性/判别式全都跟着编译器走。
 *
 * ## 两条约定
 *
 * 1. **`bindings.ts` 不许手改**（文件头写着 "Do not edit this file manually."），
 *    它是 `pnpm bindings` 的产物。类型对不上时改这里或改 UI，不要去改它。
 * 2. **serde 相位**：specta 为每个 DTO 导出 `_Serialize` / `_Deserialize` 两个变体，
 *    两者只在"字段有没有 `#[serde(default)]`/`skip_serializing_if`"上不同：
 *    - 命令**返回**的值 → `_Serialize`（例如 `Job_Serialize as Job`）；
 *    - 命令**接收**的入参 → `_Deserialize`（例如 `SettingsPatch_Deserialize as SettingsPatch`）。
 *    选错相位不会报错，但会把"后端保证一定有"的字段标成可选（反之亦然），
 *    所以每个别名后面都注明了理由。
 *
 * 注意：`Settings` 系的字段在 TS 里都是可选的 —— 因为 Rust 那边每个字段都有
 * `#[serde(default)]`，specta 就把它们标成可选。**运行时后端一定会发出这些字段**
 * （`default` 只影响反序列化），所以 UI 里用 `?? 兜底值` 只是为了让类型收敛，
 * 不是真的在处理缺字段。
 */

/**
 * 给下面几个"按 kind 收窄"的工具类型用的本地别名。
 *
 * 曾经这里有 7 个别名，其中 5 个是给**手写的 `AppEvent`** 用的。
 * `AppEvent` 改为从 bindings 再导出之后（见文件末尾），那 5 个就不需要了 ——
 * 这本身就是"手写契约消失"的一个可见信号。
 */
import type {
  Capability as EventCapability,
  JobKind as EventJobKind,
} from "@/bindings";

// ============================================================================
// 任务（`Job_Serialize`：命令返回值）
// ============================================================================

export type {
  Job_Serialize as Job,
  JobProgress_Serialize as JobProgress,
  JobsSnapshot_Serialize as JobsSnapshot,
  JobLogEntry,
  JobKind,
  JobStatus,
  JobId,
  LogLevel,
  JobStats,
  // 入参相位：`jobs_list` 接收的是 `JobsListRequest_Deserialize`
  JobsListRequest_Deserialize as JobsListRequest,
  JobFilter_Deserialize as JobFilter,
} from "@/bindings";

// ============================================================================
// 引擎
// ============================================================================

export type {
  EngineDescriptor_Serialize as EngineDescriptor,
  EngineModel_Serialize as EngineModel,
  EngineStatus_Serialize as EngineStatus,
  EngineEntry_Serialize as EngineEntry,
  EngineState,
  EngineSource,
  EngineInstallMode,
  // 入参：只有一种形状（没有 default 字段）
  EngineInstallRequest,
} from "@/bindings";

// ============================================================================
// 模型权重
// ============================================================================

export type {
  ModelEntry_Serialize as ModelEntry,
  // 入参：只有一种形状
  ModelInstallRequest,
} from "@/bindings";

// ============================================================================
// 权限与能力（能力模型本身没有相位差异）
// ============================================================================

export type {
  PermissionSet,
  Capability,
  PathScope,
  RiskLevel,
} from "@/bindings";

// ============================================================================
// 插件
// ============================================================================

export type {
  PluginManifest_Serialize as PluginManifest,
  PluginMetadata_Serialize as PluginMetadata,
  PluginRuntime_Serialize as PluginRuntime,
  PluginIo_Serialize as PluginIo,
  IoPort_Serialize as IoPort,
  ParamSpec_Serialize as ParamSpec,
  PluginSummary_Serialize as PluginSummary,
  PluginDetail_Serialize as PluginDetail,
  ValidationReport_Serialize as ValidationReport,
  ValidationIssue_Serialize as ValidationIssue,
  InstallReport_Serialize as InstallReport,
  PluginsSnapshot_Serialize as PluginsSnapshot,
  ValidatePluginResponse_Serialize as ValidatePluginResponse,
  AuditEvent_Serialize as AuditEvent,
  AuditSnapshot_Serialize as AuditSnapshot,
  // 无相位差异
  PluginCategory,
  RuntimeKind,
  PortType,
  ParamType,
  ParamOption,
  ParamValue,
  Severity,
  PluginSource,
  BundleFile,
  FileEncoding,
  AuditEventKind,
  ValidatePluginRequest,
  InstallPluginRequest,
  GrantPermissionsRequest,
  RunPluginRequest,
  RunPluginResponse,
} from "@/bindings";

// ============================================================================
// 流程（节点目录 + 流水线定义）
// ============================================================================

export type {
  NodeDescriptor_Serialize as NodeDescriptor,
  NodeCatalogResponse_Serialize as NodeCatalogResponse,
  PipelineDef_Serialize as PipelineDef,
  PipelineStep_Serialize as PipelineStep,
  // 无相位差异
  NodeCategory,
  OnErrorPolicy,
  StepPosition,
  WasmRuntimeDef,
  PythonRuntimeDef,
} from "@/bindings";

// ============================================================================
// AI
// ============================================================================

export type {
  SecurityReview_Serialize as SecurityReview,
  ReviewFinding_Serialize as ReviewFinding,
  AiGenerateResponse_Serialize as AiGenerateResponse,
  AiTestConnectionResponse_Serialize as AiTestConnectionResponse,
  AiProvenance_Serialize as AiProvenance,
  // 入参相位：`ai_generate` 接收的是 `AiGenerateRequest_Deserialize`
  AiGenerateRequest_Deserialize as AiGenerateRequest,
  // 无相位差异
  AiDraft,
  DraftFile,
  AiProviderKind,
  AiSettings,
} from "@/bindings";

// ============================================================================
// 应用 / 设置 / 系统
// ============================================================================

export type {
  AppInfo,
  PathEntry,
  AppPathsDto,
  Settings,
  SystemStatus,
  // 入参相位：`settings_patch` 接收的是 `SettingsPatch_Deserialize`
  SettingsPatch_Deserialize as SettingsPatch,
  // 错误（命令返回值用的是 `_Serialize`）
  ToolforgeError_Serialize as ToolforgeError,
  ErrorCode,
} from "@/bindings";

/**
 * 后端导出的常量，直接转出去 —— 不在前端抄一遍。
 * （`EVENT_CHANNEL = "toolforge://event"`、`PLUGIN_API_VERSION = "toolforge/v1"`）
 */
export { EVENT_CHANNEL, PLUGIN_API_VERSION } from "@/bindings";

// ============================================================================
// 以下为**前端独有**的概念（Rust 侧没有对应类型）
// ============================================================================

/** 主题档位：`system` 会跟随操作系统 */
export type ThemeMode = "system" | "light" | "dark";

/** 强调色（只影响 CSS 变量，不涉及后端语义） */
export type AccentName = "cyan" | "violet" | "emerald" | "amber" | "rose";

/**
 * 用户可自行修复的错误码 → UI 上给"去设置 / 去安装"的入口。
 *
 * 与 `error.rs` 的 `ErrorCode::is_user_actionable()` 同口径（那边是 Rust 的判断，
 * 这里是给界面用的集合）。
 */
export const ACTIONABLE_CODES = [
  "ENGINE_MISSING",
  "PERMISSION_DENIED",
  "AI_UNAVAILABLE",
  "INVALID_ARGUMENT",
] as const;

// ============================================================================
// 事件（`toolforge://event`）
// ============================================================================

/**
 * 事件负载 —— **由后端生成，不再手写**。
 *
 * ## 为什么它一度是手写的，以及为什么现在不是了
 *
 * 本项目的领域事件全部发在同一个通道上（`toolforge://event`），载荷是带
 * `type` 判别式的 `AppEvent` 枚举。这种"单通道 + 判别联合"的形态**不符合**
 * `tauri-specta` 的 `collect_events!` 模型（那要求"每个事件一个实现了
 * `Event` trait 的类型"），所以 `specta_builder()` 里那个宏是空的 ——
 * 而宏为空就意味着 `bindings.ts` 里没有 `AppEvent`，前端只能手写一份。
 *
 * 手写意味着：后端把 `errorMessage` 改成 `error`，**TypeScript 不会报错**，
 * 只会在运行时静默拿到 `undefined`。这正是本项目其它地方费力消灭的漂移，
 * 没理由在这里留一个。
 *
 * 解法是 `Builder::typ::<AppEvent>()`（`lib.rs::specta_builder`）：它把类型
 * 加进导出集合，**不改事件注册机制**。一行解决。
 *
 * ## 用哪个相位
 *
 * 事件是**后端 → 前端**，所以取 `_Serialize`（与 `lib/ipc.ts` 里
 * "返回值用 `_Serialize`、入参用 `_Deserialize`" 的约定一致）。
 * 生成的联合还带了 `& { <其他变体的键>?: never }` 守卫，比手写版收窄得更准。
 */
export type { AppEvent_Serialize as AppEvent } from "@/bindings";

import type { AppEvent_Serialize } from "@/bindings";

export type AppEventType = AppEvent_Serialize["type"];

// ============================================================================
// 派生工具类型
// ============================================================================

export type JobOfKind<K extends EventJobKind["kind"]> = Extract<EventJobKind, { kind: K }>;

export type CapabilityOfKind<K extends EventCapability["kind"]> = Extract<
  EventCapability,
  { kind: K }
>;
