/**
 * # 领域类型：**唯一真相来源是 `src/bindings.ts`**
 *
 * 这个文件现在只是一层**薄薄的别名层**，不再自己定义任何镜像 Rust 的结构：
 *
 * ```text
 * Rust 类型 ──(tauri-specta / pnpm bindings)──► src/bindings.ts ──► 本文件的别名
 * ```
 *
 * 为什么这么做：手写一份"镜像类型"意味着**两套真相**。后端改一个字段名，
 * 手写这份照旧编译通过，运行时才炸 —— 而且是在用户点下按钮之后才炸。
 * 生成的 bindings 是从真实 Rust 类型导出的，字段名/可选性/判别式全都跟着编译器走。
 *
 * ## 两条约定
 *
 * 1. **`bindings.ts` 不许手改**（文件头写着 "Do not edit this file manually."），
 *    它是 `pnpm bindings` 的产物。类型对不上时改这里或改 UI，不要去改它。
 * 2. **serde 相位**：specta 为每个 DTO 导出 `_Serialize` / `_Deserialize` 两个变体，
 *    两者只在"字段有没有 `#[serde(default)]`/`skip_serializing_if`"上不同：
 *    - 命令**返回**的值 → `_Serialize`（例如 `Job_Serialize as Job`）；
 *    - 命令**接收**的入参 → `_Deserialize`（例如 `SettingsPatch_Deserialize as SettingsPatch`）。
 *    选错相位不会报错，但会把"后端保证一定有"的字段标成可选（反之亦然），
 *    所以每个别名后面都注明了理由。
 *
 * 注意：`Settings` 系的字段在 TS 里都是可选的 —— 因为 Rust 那边每个字段都有
 * `#[serde(default)]`，specta 就把它们标成可选。**运行时后端一定会发出这些字段**
 * （`default` 只影响反序列化），所以 UI 里用 `?? 兜底值` 只是为了让类型收敛，
 * 不是真的在处理缺字段。
 */

/**
 * 给 `AppEvent` 用的本地别名：事件载荷里嵌的是**同一批生成类型**，
 * 这里 import 一次、起个不会和下面的再导出撞名的名字，
 * 免得满文件写 `import("@/bindings")` 这种内联类型。
 */
import type {
  Capability as EventCapability,
  EngineStatus_Serialize as EventEngineStatus,
  JobKind as EventJobKind,
  JobLogEntry as EventJobLogEntry,
  JobProgress_Serialize as EventJobProgress,
  JobStatus as EventJobStatus,
  Job_Serialize as EventJob,
} from "@/bindings";

// ============================================================================
// 任务（`Job_Serialize`：命令返回值）
// ============================================================================

export type {
  Job_Serialize as Job,
  JobProgress_Serialize as JobProgress,
  JobsSnapshot_Serialize as JobsSnapshot,
  JobLogEntry,
  JobKind,
  JobStatus,
  JobId,
  LogLevel,
  JobStats,
  // 入参相位：`jobs_list` 接收的是 `JobsListRequest_Deserialize`
  JobsListRequest_Deserialize as JobsListRequest,
  JobFilter_Deserialize as JobFilter,
} from "@/bindings";

// ============================================================================
// 引擎
// ============================================================================

export type {
  EngineDescriptor_Serialize as EngineDescriptor,
  EngineModel_Serialize as EngineModel,
  EngineStatus_Serialize as EngineStatus,
  EngineEntry_Serialize as EngineEntry,
  EngineState,
  EngineSource,
  EngineInstallMode,
  // 入参：只有一种形状（没有 default 字段）
  EngineInstallRequest,
} from "@/bindings";

// ============================================================================
// 权限与能力（能力模型本身没有相位差异）
// ============================================================================

export type {
  PermissionSet,
  Capability,
  PathScope,
  RiskLevel,
} from "@/bindings";

// ============================================================================
// 插件
// ============================================================================

export type {
  PluginManifest_Serialize as PluginManifest,
  PluginMetadata_Serialize as PluginMetadata,
  PluginRuntime_Serialize as PluginRuntime,
  PluginIo_Serialize as PluginIo,
  IoPort_Serialize as IoPort,
  ParamSpec_Serialize as ParamSpec,
  PluginSummary_Serialize as PluginSummary,
  PluginDetail_Serialize as PluginDetail,
  ValidationReport_Serialize as ValidationReport,
  ValidationIssue_Serialize as ValidationIssue,
  InstallReport_Serialize as InstallReport,
  PluginsSnapshot_Serialize as PluginsSnapshot,
  ValidatePluginResponse_Serialize as ValidatePluginResponse,
  AuditEvent_Serialize as AuditEvent,
  AuditSnapshot_Serialize as AuditSnapshot,
  // 无相位差异
  PluginCategory,
  RuntimeKind,
  PortType,
  ParamType,
  ParamOption,
  ParamValue,
  Severity,
  PluginSource,
  BundleFile,
  FileEncoding,
  AuditEventKind,
  ValidatePluginRequest,
  InstallPluginRequest,
  GrantPermissionsRequest,
  RunPluginRequest,
  RunPluginResponse,
} from "@/bindings";

// ============================================================================
// 流程（节点目录 + 流水线定义）
// ============================================================================

export type {
  NodeDescriptor_Serialize as NodeDescriptor,
  NodeCatalogResponse_Serialize as NodeCatalogResponse,
  PipelineDef_Serialize as PipelineDef,
  PipelineStep_Serialize as PipelineStep,
  // 无相位差异
  NodeCategory,
  OnErrorPolicy,
  StepPosition,
  WasmRuntimeDef,
  PythonRuntimeDef,
} from "@/bindings";

// ============================================================================
// AI
// ============================================================================

export type {
  SecurityReview_Serialize as SecurityReview,
  ReviewFinding_Serialize as ReviewFinding,
  AiGenerateResponse_Serialize as AiGenerateResponse,
  AiTestConnectionResponse_Serialize as AiTestConnectionResponse,
  AiProvenance_Serialize as AiProvenance,
  // 入参相位：`ai_generate` 接收的是 `AiGenerateRequest_Deserialize`
  AiGenerateRequest_Deserialize as AiGenerateRequest,
  // 无相位差异
  AiDraft,
  DraftFile,
  AiProviderKind,
  AiSettings,
} from "@/bindings";

// ============================================================================
// 应用 / 设置 / 系统
// ============================================================================

export type {
  AppInfo,
  PathEntry,
  AppPathsDto,
  Settings,
  SystemStatus,
  // 入参相位：`settings_patch` 接收的是 `SettingsPatch_Deserialize`
  SettingsPatch_Deserialize as SettingsPatch,
  // 错误（命令返回值用的是 `_Serialize`）
  ToolforgeError_Serialize as ToolforgeError,
  ErrorCode,
} from "@/bindings";

/**
 * 后端导出的常量，直接转出去 —— 不在前端抄一遍。
 * （`EVENT_CHANNEL = "toolforge://event"`、`PLUGIN_API_VERSION = "toolforge/v1"`）
 */
export { EVENT_CHANNEL, PLUGIN_API_VERSION } from "@/bindings";

// ============================================================================
// 以下为**前端独有**的概念（Rust 侧没有对应类型）
// ============================================================================

/** 主题档位：`system` 会跟随操作系统 */
export type ThemeMode = "system" | "light" | "dark";

/** 强调色（只影响 CSS 变量，不涉及后端语义） */
export type AccentName = "cyan" | "violet" | "emerald" | "amber" | "rose";

/**
 * 用户可自行修复的错误码 → UI 上给"去设置 / 去安装"的入口。
 *
 * 与 `error.rs` 的 `ErrorCode::is_user_actionable()` 同口径（那边是 Rust 的判断，
 * 这里是给界面用的集合）。
 */
export const ACTIONABLE_CODES = [
  "ENGINE_MISSING",
  "PERMISSION_DENIED",
  "AI_UNAVAILABLE",
  "INVALID_ARGUMENT",
] as const;

// ============================================================================
// 事件（`toolforge://event`）
// ============================================================================

/**
 * 事件负载。
 *
 * **为什么这里仍是手写的**：后端 `specta_builder()` 里的
 * `collect_events![]` 是空的（事件靠 `app.emit` 手发，没走 specta 注册），
 * 所以 `bindings.ts` 里**没有** `AppEvent`。这个类型是唯一一处手写契约，
 * 核对来源是 `crates/toolforge-core/src/events.rs`：
 *
 * - tag 是 `"type"`，变体名 camelCase；
 * - 后端加了 `rename_all_fields = "camelCase"`，所以**载荷字段是 camelCase**：
 *   `jobId` / `errorMessage` / `engineId` / `speedBps` / `requestId` / `pluginId`；
 * - 内嵌的 `Job` / `JobProgress` / `EngineStatus` 等直接用从 bindings 转出来的
 *   同名类型（见上面的 import），所以只有"字段名"这一层是手写的，
 *   结构本身仍然跟着生成类型走；
 * - `Option<T>` + `skip_serializing_if` 的字段（`errorMessage` / `subject` /
 *   `error` / `message`）为空时**整个键不出现**，所以是可选的。
 *
 * `use-events.ts` 在这里统一做"camelCase 优先、snake_case 兜底"的读取，
 * 万一后端回退 `rename_all_fields` 也不会整体失灵。
 */
export type AppEvent =
  | { type: "jobUpdated"; job: EventJob }
  | { type: "jobProgressHint"; jobId: string; progress: EventJobProgress }
  | { type: "jobLog"; jobId: string; entry: EventJobLogEntry }
  | {
      type: "jobFinished";
      jobId: string;
      status: EventJobStatus;
      title: string;
      errorMessage?: string;
    }
  | { type: "engineStatusChanged"; status: EventEngineStatus }
  | {
      type: "engineDownloadProgress";
      engineId: string;
      downloaded: number;
      total: number;
      speedBps: number;
    }
  | { type: "pluginChanged"; pluginId: string }
  | { type: "pluginLog"; pluginId: string; level: string; message: string }
  | {
      type: "securityAlert";
      severity: string;
      title: string;
      detail: string;
      subject?: string;
    }
  | { type: "aiDelta"; requestId: string; delta: string }
  | { type: "aiDone"; requestId: string; error?: string }
  | { type: "toast"; level: string; title: string; message?: string };

export type AppEventType = AppEvent["type"];

// ============================================================================
// 派生工具类型
// ============================================================================

export type JobOfKind<K extends EventJobKind["kind"]> = Extract<EventJobKind, { kind: K }>;

export type CapabilityOfKind<K extends EventCapability["kind"]> = Extract<
  EventCapability,
  { kind: K }
>;
